//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SIA_Presupuesto.Negocio.Entidades;
    using SIA_Presupuesto.Negocio.Contratos.Base;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public interface IContexto : IUnidadTrabajo
    {
    	DbSet<TEntitidad> Establecer<TEntitidad>() where TEntitidad : class;
    	DbEntityEntry Entrada(object entidad);
        DbSet<Direccion> Direccion { get; set; }
        DbSet<Subdireccion> Subdireccion { get; set; }
        DbSet<CuentaContable> CuentaContable { get; set; }
        DbSet<PlanCuenta> PlanCuenta { get; set; }
        DbSet<Area> Area { get; set; }
        DbSet<Producto> Producto { get; set; }
        DbSet<Unidad> Unidad { get; set; }
        DbSet<Moneda> Moneda { get; set; }
        DbSet<GrupoCuentaDetalle> GrupoCuentaDetalle { get; set; }
        DbSet<GrupoCuentaPresupuesto> GrupoCuentaPresupuesto { get; set; }
        DbSet<TipoCambioPresupuesto> TipoCambioPresupuesto { get; set; }
        DbSet<RequerimientoBienServicio> RequerimientoBienServicio { get; set; }
        DbSet<DenomCuenta> DenomCuenta { get; set; }
        DbSet<Denominador> Denominador { get; set; }
        DbSet<ProductoDenominador> ProductoDenominador { get; set; }
        DbSet<ProgramacionAnualAreaMes> ProgramacionAnualAreaMes { get; set; }
        DbSet<ProgramacionAnualArea> ProgramacionAnualArea { get; set; }
        DbSet<EvaluacionMensualAreaMes> EvaluacionMensualAreaMes { get; set; }
        DbSet<EvaluacionMensualDetalle> EvaluacionMensualDetalle { get; set; }
        DbSet<EvaluacionMensualProgramacionArea> EvaluacionMensualProgramacionArea { get; set; }
        DbSet<ReajusteMensualArea> ReajusteMensualArea { get; set; }
        DbSet<ReajusteMensualAreaMes> ReajusteMensualAreaMes { get; set; }
        DbSet<ReajusteMensualProgramacionArea> ReajusteMensualProgramacionArea { get; set; }
        DbSet<EvaluacionMensualDetalleMes> EvaluacionMensualDetalleMes { get; set; }
        DbSet<ConfiguracionPAA> ConfiguracionPAA { get; set; }
        DbSet<FuenteFinanciamiento> FuenteFinanciamiento { get; set; }
        DbSet<PlanAnualAdquisicionDetalleMes> PlanAnualAdquisicionDetalleMes { get; set; }
        DbSet<TipoConfiguracionPAA> TipoConfiguracionPAA { get; set; }
        DbSet<Ubigeo> Ubigeo { get; set; }
        DbSet<PlanAnualAdquisicionRequerimiento> PlanAnualAdquisicionRequerimiento { get; set; }
        DbSet<PlanAnualAdquisicion> PlanAnualAdquisicion { get; set; }
        DbSet<PlanAnualAdquisicionDetalle> PlanAnualAdquisicionDetalle { get; set; }
        DbSet<GastoRecurrente> GastoRecurrente { get; set; }
        DbSet<GastoRecurrenteDetalle> GastoRecurrenteDetalle { get; set; }
        DbSet<GastoRecurrenteDetalleMes> GastoRecurrenteDetalleMes { get; set; }
        DbSet<GastoRecurrenteRequerimiento> GastoRecurrenteRequerimiento { get; set; }
        DbSet<RubroBienServicio> RubroBienServicio { get; set; }
        DbSet<RubroBienServicioCuenta> RubroBienServicioCuenta { get; set; }
        DbSet<EvaluacionMensualProgramacionPres> EvaluacionMensualProgramacionPres { get; set; }
        DbSet<EvaluacionMensualProgramacion> EvaluacionMensualProgramacion { get; set; }
        DbSet<EvaluacionMensualArea> EvaluacionMensualArea { get; set; }
        DbSet<TipoReporte> TipoReporte { get; set; }
        DbSet<TipoReporteGrupoFinan> TipoReporteGrupoFinan { get; set; }
        DbSet<Presupuesto> Presupuesto { get; set; }
        DbSet<GrupoFinanciamiento> GrupoFinanciamiento { get; set; }
        DbSet<GrupoFinanciamientoDetalle> GrupoFinanciamientoDetalle { get; set; }
        DbSet<ProgramacionAnualGastoDetalleMes> ProgramacionAnualGastoDetalleMes { get; set; }
        DbSet<ProgramacionAnualPlanAdqDetalleMes> ProgramacionAnualPlanAdqDetalleMes { get; set; }
        DbSet<RequerimientoBienServicioDetalleMes> RequerimientoBienServicioDetalleMes { get; set; }
        DbSet<ForebiDetalle> ForebiDetalle { get; set; }
        DbSet<ForeseDetalle> ForeseDetalle { get; set; }
        DbSet<EjeOperativo> EjeOperativo { get; set; }
        DbSet<Modalidad> Modalidad { get; set; }
        DbSet<SedeLaboral> SedeLaboral { get; set; }
        DbSet<ProgramacionAnualSede> ProgramacionAnualSede { get; set; }
        DbSet<ProgramacionAnualEjeOperativo> ProgramacionAnualEjeOperativo { get; set; }
        DbSet<ReajusteProgramacionMensualDetalleMes> ReajusteProgramacionMensualDetalleMes { get; set; }
        DbSet<ReportePresupuesto> ReportePresupuesto { get; set; }
        DbSet<ReportePresupuestoDetalle> ReportePresupuestoDetalle { get; set; }
        DbSet<TipoReporteGrupoPresupuesto> TipoReporteGrupoPresupuesto { get; set; }
        DbSet<PresupuestoRecepcionado> PresupuestoRecepcionado { get; set; }
        DbSet<GrupoPresupuesto> GrupoPresupuesto { get; set; }
        DbSet<EstructuraPresupuestoRemuneracion> EstructuraPresupuestoRemuneracion { get; set; }
        DbSet<ParametroPresupuestoRemuneracion> ParametroPresupuestoRemuneracion { get; set; }
        DbSet<PresupuestoRemuneracion> PresupuestoRemuneracion { get; set; }
        DbSet<PropiedadPresupuestoRemuneracion> PropiedadPresupuestoRemuneracion { get; set; }
        DbSet<PresupuestoRemuneracionDet> PresupuestoRemuneracionDet { get; set; }
        DbSet<Cargo> Cargo { get; set; }
        DbSet<OrigenConcepto> OrigenConcepto { get; set; }
        DbSet<ConceptoCuentaContable> ConceptoCuentaContable { get; set; }
        DbSet<ConceptoPresupuestoRemuneracion> ConceptoPresupuestoRemuneracion { get; set; }
        DbSet<ReajustePresupuestoRemuneracion> ReajustePresupuestoRemuneracion { get; set; }
        DbSet<ReajusteMensualProgramacion> ReajusteMensualProgramacion { get; set; }
        DbSet<ReajustePresupuestoRemuneracionDet> ReajustePresupuestoRemuneracionDet { get; set; }
        DbSet<TipoCambioAnual> TipoCambioAnual { get; set; }
        DbSet<PuestoReajustePresupuesto> PuestoReajustePresupuesto { get; set; }
        DbSet<Periodo> Periodo { get; set; }
        DbSet<Subpresupuesto> Subpresupuesto { get; set; }
        DbSet<CertificacionMaster> CertificacionMaster { get; set; }
        DbSet<Forebi> Forebi { get; set; }
        DbSet<Forese> Forese { get; set; }
        DbSet<CertificacionDetalle> CertificacionDetalle { get; set; }
        DbSet<RequerimientoRecursoHumano> RequerimientoRecursoHumano { get; set; }
        DbSet<PuestoRequerimiento> PuestoRequerimiento { get; set; }
        DbSet<ReajusteMensualDetalleMes> ReajusteMensualDetalleMes { get; set; }
        DbSet<ProgramacionAnualDetalleMes> ProgramacionAnualDetalleMes { get; set; }
        DbSet<PartidaPresupuestal> PartidaPresupuestal { get; set; }
        DbSet<RequerimientoBienServicioDetalle> RequerimientoBienServicioDetalle { get; set; }
        DbSet<RequerimientoReajusteMensual> RequerimientoReajusteMensual { get; set; }
        DbSet<ReajusteMensualDetalle> ReajusteMensualDetalle { get; set; }
        DbSet<RequerimientoMensualBienServicio> RequerimientoMensualBienServicio { get; set; }
        DbSet<RequerimientoMensualDetalle> RequerimientoMensualDetalle { get; set; }
        DbSet<PartidaPresupuestalCuenta> PartidaPresupuestalCuenta { get; set; }
        DbSet<PuestoReqPre> PuestoReqPre { get; set; }
        DbSet<CertificacionRequerimientoSubprespuesto> CertificacionRequerimientoSubprespuesto { get; set; }
        DbSet<vCotizacionCompra> vCotizacionCompra { get; set; }
        DbSet<vCotizacionDetalleCompra> vCotizacionDetalleCompra { get; set; }
        DbSet<vCotizacionDetalleServicio> vCotizacionDetalleServicio { get; set; }
        DbSet<vCotizacionServicio> vCotizacionServicio { get; set; }
        DbSet<CertificacionRequerimiento> CertificacionRequerimiento { get; set; }
        DbSet<PuestoPresupuesto> PuestoPresupuesto { get; set; }
        DbSet<ProgramacionAnualDetalle> ProgramacionAnualDetalle { get; set; }
        DbSet<ProgramacionAnual> ProgramacionAnual { get; set; }
        DbSet<PoaVersion> PoaVersion { get; set; }
        DbSet<TipoActividad> TipoActividad { get; set; }
        DbSet<Poa> Poa { get; set; }
    		 ObjectResult<ProgramacionAnualPres> TraerListaProgramacionAnual(Nullable<int> anio);
    			
    		
    		 ObjectResult<ProgramacionAnualAreaPres> TraerListaProgramacionAnualArea(Nullable<int> idProAnu);
    			
    		
    		 ObjectResult<ProgramacionAnualDetallePres> TraerListaProgramacionAnualDetalle(Nullable<int> idProAnuArea);
    			
    		
    		 ObjectResult<ProgramacionAnualDetallePres> TraerListaProgramacionAnualDetallePorPresupuesto(Nullable<int> idProAnu);
    			
    		
    		 ObjectResult<ProgramacionAnualAreaExporta> TraerListaProgramacionAnualAreaExporta(Nullable<int> idProAnu);
    			
    		
    		 ObjectResult<EvaluacionMensualAreaPres> TraerListaEvaluacionMensualArea(Nullable<int> idEvaMenPro);
    			
    		
    		 ObjectResult<EvaluacionMensualAreaExporta> TraerListaEvaluacionMensualAreaExporta(Nullable<int> idEvaMenPro);
    			
    		
    		 ObjectResult<EvaluacionMensualDetallePres> TraerListaEvaluacionMensualDetalle(Nullable<int> idEvaMenArea);
    			
    		
    		 ObjectResult<EvaluacionMensualDetallePres> TraerListaEvaluacionMensualDetallePorPresupuesto(Nullable<int> idEvaMenPro);
    			
    		
    		 ObjectResult<EvaluacionMensualPresupuestoPres> TraerListaEvaluacionMensualPresupuesto(Nullable<int> anio, Nullable<int> mes);
    			
    		
    		 ObjectResult<RequerimientoBienServicioPres> TraerListaRequerimientoBienServicio(Nullable<int> anio, Nullable<int> idUsuario);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetallePres> TraerListaRequerimientoBienServicioDetalle(Nullable<int> idReqBieSer);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetallePres> TraerListaRequerimientoBienServicioDetalleDireccion(Nullable<int> idDireccion, Nullable<int> idSubdireccion, Nullable<int> anio, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<PlanAnualAdquisicionDetallePres> TraerListaPlanAnualAdquisicionDetalle(Nullable<int> idPaa);
    			
    		
    		 ObjectResult<PlanAnualAdquisicionRequerimientoPres> TraerListaPlanAnualAdquisicionRequerimiento(Nullable<int> idPaa);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetalleMes> TraerListaRequerimientoBienServicioDetalleMesPendiente(Nullable<int> idReqBieSerDet, Nullable<int> tipoRubro);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetalleMes> TraerListaRequerimientoBienServicioDetalleMesPendiente(Nullable<int> idReqBieSerDet, Nullable<int> tipoRubro, MergeOption mergeOption);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetalle> TraerListaRequerimientoBienServicioDetallePendiente(Nullable<int> idReqBieSer);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetalle> TraerListaRequerimientoBienServicioDetallePendiente(Nullable<int> idReqBieSer, MergeOption mergeOption);
    			
    		
    		 ObjectResult<RequerimientoBienServicio> TraerListaRequerimientoBienServicioPendiente(Nullable<int> idPaa);
    			
    		
    		 ObjectResult<RequerimientoBienServicio> TraerListaRequerimientoBienServicioPendiente(Nullable<int> idPaa, MergeOption mergeOption);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetallePresExporta> TraerListaRequerimientoBienServicioDetalleDireccionExporta(Nullable<int> idDireccion, Nullable<int> anio);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetalleExporta> TraerListaRequerimientoBienServicioDetalleExporta(Nullable<int> idDireccion, Nullable<int> anio);
    			
    		
    		 ObjectResult<ProgramacionAnualPres> TraerListaProgramacionAnualAprobados(Nullable<int> anio);
    			
    		
    		 ObjectResult<RequerimientoBienServicioPendientePorCuentaPres> TraerListaRequerimientoBienServicioPendientePorCuenta(Nullable<int> idCueCon, Nullable<int> anio, Nullable<int> tipoRubro);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetallePresExporta> TraerListaRequerimientoBienServicioDetalleDireccionAreaExporta(Nullable<int> idDireccion, Nullable<int> anio);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetalleExporta> TraerListaRequerimientoBienServicioDetalleAreaExporta(Nullable<int> idDireccion, Nullable<int> anio);
    			
    		
    		 ObjectResult<ReportePlanAnualAdquisicionDetallePres> TraerReportePlanAnualAdquisicionDetalle(Nullable<int> idPaa, Nullable<int> idFueFin);
    			
    		
    		 ObjectResult<CuentaContable> TraerListaCuentaContableRequerimientoBienServicio(Nullable<int> anio, Nullable<int> idCueCon, Nullable<int> nivel, Nullable<int> tipoRubro);
    			
    		
    		 ObjectResult<CuentaContable> TraerListaCuentaContableRequerimientoBienServicio(Nullable<int> anio, Nullable<int> idCueCon, Nullable<int> nivel, Nullable<int> tipoRubro, MergeOption mergeOption);
    			
    		
    		 ObjectResult<FondoEjecutado> TraerFondoEjecutados(Nullable<int> idMoneda, Nullable<int> anio, Nullable<int> mesInicio, Nullable<int> mesFin, string codigos);
    			
    		
    		 ObjectResult<GastoRecurrenteDetallePres> TraerListaGastoRecurrenteDetalle(Nullable<int> idGasRec);
    			
    		
    		 ObjectResult<GastoRecurrenteRequerimientoPres> TraerListaGastoRecurrenteRequerimiento(Nullable<int> idGasRec);
    			
    		
    		 ObjectResult<ReporteGastoRecurrenteDetallePres> TraerReporteGastoRecurrenteDetalle(Nullable<int> idGasRec);
    			
    		
    		 ObjectResult<CuentaContable> TraerListaCuentaContableRubro(Nullable<int> tipoRubro, Nullable<int> anio);
    			
    		
    		 ObjectResult<CuentaContable> TraerListaCuentaContableRubro(Nullable<int> tipoRubro, Nullable<int> anio, MergeOption mergeOption);
    			
    		
    		 ObjectResult<ReporteGastoRecurrenteDetalleDireccionPres> TraerReporteGastoRecurrenteDetalleDireccion(Nullable<int> idgasrec, Nullable<int> idDireccion);
    			
    		
    		 ObjectResult<GrupoPresupuestoPres> TraerListaGrupoPresupuestoPres();
    			
    		
    		 ObjectResult<PresupuestoPres> TraerListaPresupuestoPres();
    			
    		
    		 int GuardarFondoEjecutados(Nullable<int> id, string usuario, Nullable<int> idMoneda, Nullable<int> anio, Nullable<int> mesInicio, Nullable<int> mesFin, string codigos);
    			
    		
    		 ObjectResult<ResumenEvaFinanCorahSaal> TraerResumenEvaFinanCorahSaal(Nullable<int> idTipRep, Nullable<int> anio, Nullable<int> mes);
    			
    		
    		 ObjectResult<ReporteOrdenCompraServicioComprometidasPres> TraerReporteOrdenCompraServicioComprometidas(Nullable<int> anio);
    			
    		
    		 ObjectResult<Nullable<bool>> ActualizarDetallesPac(Nullable<int> idPaa, string nomUsuario);
    			
    		
    		 ObjectResult<ReajusteMensualAreaPres> TraerListaReajusteMensualArea(Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<ReajusteMensualAreaExporta> TraerListaReajusteMensualAreaExporta(Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<ReajusteMensualDetallePres> TraerListaReajusteMensualDetalle(Nullable<int> idEvaMenArea);
    			
    		
    		 ObjectResult<ReajusteMensualDetallePres> TraerListaReajusteMensualDetallePorPresupuesto(Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<ReajusteMensualPresupuestoPres> TraerListaReajusteMensualPresupuesto(Nullable<int> anio, Nullable<int> mes);
    			
    		
    		 ObjectResult<Nullable<bool>> ActualizarDetallesGastoRecurrente(Nullable<int> idGasRec, string nomUsuario);
    			
    		
    		 int GuardarDetalleReajuste(Nullable<int> idProAnu, Nullable<int> idReaMenPro, string usuario);
    			
    		
    		 ObjectResult<GrupoPresupuesto> TraerListaGrupoPresupuesto();
    			
    		
    		 ObjectResult<GrupoPresupuesto> TraerListaGrupoPresupuesto(MergeOption mergeOption);
    			
    		
    		 ObjectResult<Presupuesto> TraerListaPresupuestoPorGrupoPresupuesto(Nullable<int> idGruPre);
    			
    		
    		 ObjectResult<Presupuesto> TraerListaPresupuestoPorGrupoPresupuesto(Nullable<int> idGruPre, MergeOption mergeOption);
    			
    		
    		 ObjectResult<Subpresupuesto> TraerListaSubPresupuestoPorPresupuesto(Nullable<int> idPresupuesto);
    			
    		
    		 ObjectResult<Subpresupuesto> TraerListaSubPresupuestoPorPresupuesto(Nullable<int> idPresupuesto, MergeOption mergeOption);
    			
    		
    		 ObjectResult<FondoEjecutadosSubpresupuesto> TraerFondoEjecutadosSubpresupuesto(Nullable<int> idMoneda, Nullable<int> idGruPre, Nullable<int> idPresupuesto, Nullable<int> idSubpresupuesto);
    			
    		
    		 ObjectResult<ReporteOrdenCompraServicioPresupuestoPres> TraerReporteOrdenCompraServicioPresupuesto(Nullable<int> anio, Nullable<int> idPresupuesto, Nullable<int> nivel, Nullable<int> opcion);
    			
    		
    		 ObjectResult<ReportePlanAnualAdquisicionDireccionPres> TraerReportePlanAnualAdquisicionDireccion(Nullable<int> idPaa, Nullable<int> idDireccion, Nullable<int> idFueFin);
    			
    		
    		 ObjectResult<FondoEjecutadoFecha> TraerFondoEjecutadosFechas(Nullable<int> idMoneda, Nullable<int> idGruPre, Nullable<int> idPresupuesto, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin);
    			
    		
    		 ObjectResult<ReporteEvaluacionDetalladaBienSerPres> TraerReporteEvaluacionDetalladaBienSer(Nullable<int> anio, Nullable<int> idGruPre, Nullable<int> idDireccion, Nullable<int> idSubDireccion);
    			
    		
    		 int GuardarDetalleProgramacionAnual(Nullable<int> idProAnu, string codigos, string usuario, Nullable<bool> indicaEliminacion);
    			
    		
    		 ObjectResult<ReporteEvaluacionDetalladaBienSerExportaPres> TraerReporteEvaluacionDetalladaBienSerExporta(Nullable<int> anio, Nullable<int> idGruPre, Nullable<int> idDireccion, Nullable<int> idSubDireccion);
    			
    		
    		 ObjectResult<EvaluacionMensualDetallePres> TraerListaEvaluacionMensualDetallePorPresupuestoPres(Nullable<int> idEvaMenPro);
    			
    		
    		 ObjectResult<ProgramacionAnualDetallePres> TraerListaProgramacionAnualDetallePorPresupuestoPres(Nullable<int> idProAnu);
    			
    		
    		 ObjectResult<ReajusteMensualDetallePres> TraerListaReajusteMensualDetallePorPresupuestoPres(Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<Nullable<int>> TraerListaProgramacionAnualAreas(Nullable<int> idProAnu);
    			
    		
    		 int GuardarDetalleProgramacionAnualGastosRecuerrentes(Nullable<int> idProAnu, string codigos, string usuario, Nullable<bool> indicaEliminacion);
    			
    		
    		 ObjectResult<RequerimientoBienServicioDetallePres> TraerListaRequerimientoBienServicioDetalleDireccionOperativos(Nullable<int> idDireccion, Nullable<int> anio, string tipo, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ConsolidadoPresupuesto> TraerConsolidadoPresupuestoPorDirecciones(Nullable<int> anio);
    			
    		
    		 ObjectResult<ResumenPresupuestoPorSubdireccion> TraerResumenPresupuestoPorSubdirecciones(Nullable<int> anio, Nullable<int> idDireccion);
    			
    		
    		 ObjectResult<CalendarioEvaluacionyAjusteAnual> TraerCalendarioEvaluacionyAjusteAnual(Nullable<int> anio, Nullable<int> idFueFin, Nullable<int> mesAjuste, Nullable<int> mesEval, Nullable<int> idPresupuesto);
    			
    		
    		 ObjectResult<CalendarioPresupuestoAnual> TraerCalendarioPresupuestoAnual(Nullable<int> anio, Nullable<int> idFueFin, Nullable<int> idPresupuesto);
    			
    		
    		 ObjectResult<ResumenReajustePresupuestoPorSubdirecciones> TraerResumenReajustePresupuestoPorSubdirecciones(Nullable<int> anio, Nullable<int> idDireccion, Nullable<int> mesReajuste, Nullable<int> mesEvaluacion);
    			
    		
    		 ObjectResult<ReportePlanAnualAdquisicionExportaPres> TraerReportePlanAnualAdquisicionExporta(Nullable<int> idPaa, Nullable<int> idDireccion, Nullable<int> idFueFin);
    			
    		
    		 ObjectResult<SubPresupuestoDetallePres> TraerListaSubPresupuestoDetalle(Nullable<int> idSubPresupuesto);
    			
    		
    		 ObjectResult<CertificacionDetallePres> TraerListaCertificacionDetalle(Nullable<int> idCerMas, Nullable<int> idCerReq);
    			
    		
    		 ObjectResult<ForeDetallePres> TraerListaFormatoRequerimientoDetalle(Nullable<int> idFore, Nullable<int> tipo);
    			
    		
    		 ObjectResult<SubPresupuestoAreaPres> TraerListaSubPresupuestoAreaPres(Nullable<int> idSubPresupuesto);
    			
    		
    		 ObjectResult<SubPresupuestoAreaDetallePres> TraerListaSubPresupuestoAreaDetallePres(Nullable<int> idSubPresupuesto);
    			
    		
    		 ObjectResult<PresupuestoPorErradicacion> TraerResumenPresupuestoPorErradicacion(Nullable<int> anio);
    			
    		
    		 ObjectResult<SubPresupuestoPres> TraerListaSubPresupuestoPres(Nullable<int> anio);
    			
    		
    		 ObjectResult<EvaluacionReajusteMensualAreaExporta> TraerListaEvaluacionReajusteMensualAreaExporta(Nullable<int> idPreoAnu, Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva);
    			
    		
    		 ObjectResult<EvaluacionReajusteMensualDetallePorPresupuesto> TraerListaEvaluacionReajusteMensualDetallePorPresupuesto(Nullable<int> idPreoAnu, Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva);
    			
    		
    		 ObjectResult<ConsolidadoEvaluacionReajuste> TraerConsolidadoEvaluacionReajustePorDirecciones(Nullable<int> anio, Nullable<int> idFueFin, Nullable<int> mesRea, Nullable<int> mesEva);
    			
    		
    		 ObjectResult<PrecioBienServicioPres> TraerListaPrecioBienServicio(Nullable<int> anio, Nullable<int> idProSer, Nullable<int> tipo);
    			
    		
    		 ObjectResult<EvaluacionReajustePorSubdireccion> TraerResumenEvaluacionReajustePorSubdirecciones(Nullable<int> anio, Nullable<int> idDireccion, Nullable<int> idGruPre, Nullable<int> mesAjuste, Nullable<int> mesEval);
    			
    		
    		 ObjectResult<EvaluacionPresupuestoDetalleMovimientosPres> TraerListaEvaluacionPresupuestoDetalleMovimientos(Nullable<int> idSubPresupuesto, string numCuenta, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<EvaluacionPresupuestoPorCuentasPres> TraerListaEvaluacionPresupuestoPorCuentas(Nullable<int> idSubPresupuesto, string numCuenta, Nullable<int> nivelCuenta, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteCertificacionPresupuestalPres> TraerReporteCertificacionPresupuestal(Nullable<int> idCerReq, Nullable<bool> esAmpliacion);
    			
    		
    		 ObjectResult<ReportePresupuestoEjecutadoFondosPres> TraerReportePresupuestoEjecutadoFondos(Nullable<int> idMoneda, Nullable<int> anio, Nullable<int> mesInicio, Nullable<int> mesFin, string numCuenta);
    			
    		
    		 ObjectResult<ReportePresupuestoAprobadoComprometidoEjecutadoPres> TraerReportePresupuestoAprobadoComprometidoEjecutado(Nullable<int> idMoneda, Nullable<int> idSubPresupuesto, Nullable<int> nivelCuenta);
    			
    		
    		 ObjectResult<EvaluacionReajusteMensualAreaExporta> TraerListaEvaluacionReajusteMensualAreaExportaMasivo(string codigos, Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva);
    			
    		
    		 ObjectResult<EvaluacionReajusteMensualDetallePorPresupuesto> TraerListaEvaluacionReajusteMensualDetallePorPresupuestoMasivo(string codigos, Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva);
    			
    		
    		 ObjectResult<SaldosEvaReaPorDir> SaldosEvaluacionReajustePorDirecciones(Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva);
    			
    		
    		 ObjectResult<DatoCalculoPresupuestoRemuneracion> TraerDatosCalculoPresupuestoRemuneracion(Nullable<int> idProAnu, Nullable<int> idEstPreRem);
    			
    		
    		 ObjectResult<DatosPuestoCalculo> TraerDatosPuestoCalculo(Nullable<int> idGruPre, Nullable<int> idPresupuesto, Nullable<int> idDireccion, Nullable<int> idSubdireccion, string condicion, Nullable<int> idProAnu);
    			
    		
    		 ObjectResult<CalculoPresupuestoRemuneracion> TraerResultadoCalculoPresupuestoRemuneracion(Nullable<int> idProAnu, Nullable<int> idEstructura);
    			
    		
    		 ObjectResult<CargoPres> TraerDatosCargo();
    			
    		
    		 ObjectResult<TrabajadorPres> TraerDatosTrabajador();
    			
    		
    		 int AnularPuestoRemuneracion(string codigos, string usuario);
    			
    		
    		 ObjectResult<DatoCategoriaLaboral> TraerDatosCategoriaLaboral();
    			
    		
    		 ObjectResult<DatoCondicionLaboral> TraerDatosCondicionLaboral();
    			
    		
    		 ObjectResult<DatoRegimenLaboral> TraerDatosRegimenLaboral();
    			
    		
    		 ObjectResult<DatoConceptoCuentaContable> TraerDatosConceptoCuentaContable(Nullable<int> idConCueCon);
    			
    		
    		 int GuardarDetalleProgramacionAnualRRHH(Nullable<int> idProAnu, string codigos, string usuario, Nullable<bool> indicaEliminacion);
    			
    		
    		 int CrearProgramacionDetalle(Nullable<int> idPreRem, Nullable<int> estado, Nullable<decimal> importe, Nullable<int> mes, Nullable<System.DateTime> fechaCrea, string usuCrea, Nullable<int> idProPreRem);
    			
    		
    		 int ModificarProgramacionDetalle(Nullable<int> idPreRemDet, Nullable<decimal> importe, Nullable<System.DateTime> fechaMod, string usuMod);
    			
    		
    		 int CrearReajusteProgramacionDetalle(Nullable<int> idReaPreRem, Nullable<int> estado, Nullable<decimal> importe, Nullable<int> mes, Nullable<System.DateTime> fechaCrea, string usuCrea, Nullable<int> idProPreRem);
    			
    		
    		 int GuardarDetalleReajusteRRHH(Nullable<int> idProAnu, Nullable<int> idReaMenPro, string codigos, string usuario, Nullable<bool> indicaEliminacion);
    			
    		
    		 int MigrarDatosProgramacionReajuste(Nullable<int> idReaMenPro, string usuario);
    			
    		
    		 int ModificarReajusteProgramacionDetalle(Nullable<int> idReaPreRemDet, Nullable<decimal> importe, Nullable<System.DateTime> fechaMod, string usuMod);
    			
    		
    		 ObjectResult<CalculoReajustePresupuestoRemuneracion> TraerResultadoCalculoReajustePresupuestoRemuneracion(Nullable<int> idReaMenPro, Nullable<int> idEstructura);
    			
    		
    		 int AnularPuestoReajusteRemuneracion(string codigos, string usuario);
    			
    		
    		 int AnularProgramacionDetalle(Nullable<int> idPreRemDet, Nullable<System.DateTime> fechaMod, string usuMod);
    			
    		
    		 int AnularProgramacionRemuneracion(Nullable<int> idPreRem, string usuario);
    			
    		
    		 int AnularReajusteProgramacionDetalle(Nullable<int> idReaPreRemDet, Nullable<System.DateTime> fechaMod, string usuMod);
    			
    		
    		 int AnularReajusteProgramacionRemuneracion(Nullable<int> idReaPreRem, string usuario);
    			
    		
    		 int CrearProgramacionRemuneracion(Nullable<int> idPuePre, Nullable<int> estado, Nullable<System.DateTime> fechaCrea, string usuCrea);
    			
    		
    		 int CrearReajusteProgramacionRemuneracion(Nullable<int> idReaPuePre, Nullable<int> estado, Nullable<System.DateTime> fechaCrea, string usuCrea);
    			
    		
    		 ObjectResult<Nullable<int>> TraerListaReajusteMensualAreas(Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<PresupuestoRemuneracionExporta> PresupuestoRemuneracionExporta(Nullable<int> idProAnu);
    			
    		
    		 ObjectResult<PresupuestoRemuneracionExporta> PresupuestoRemuneracionExportaPorGrupo(string codigosGruPre, string codigosDir, Nullable<int> anio);
    			
    		
    		 ObjectResult<PresupuestoRemuneracionExporta> ReajustePresupuestoRemuneracionExporta(Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<PresupuestoRemuneracionExporta> ReajustePresupuestoRemuneracionExportaPorGrupo(string codigosGruPre, string codigosDir, Nullable<int> anio, Nullable<int> mesReajuste);
    			
    		
    		 ObjectResult<CertificacionRequerimientoPres> TraerListaCertificacionRequerimiento(Nullable<int> idCerMas);
    			
    		
    		 ObjectResult<DatosPuestoCalculo> TraerDatosPuestoCalculoReajuste(Nullable<int> idGruPre, Nullable<int> idPresupuesto, Nullable<int> idDireccion, Nullable<int> idSubdireccion, string condicion, Nullable<int> idReaMenPro);
    			
    		
    		 ObjectResult<Nullable<bool>> AnularProgramacionAnualArea(Nullable<int> idProAnuArea, string nomUsuario);
    			
    		
    		 ObjectResult<SubPresupuestoImporteCertificacion_Pres> TraerSubPresupuestoImporteCertificacion(Nullable<int> idSubpresupuesto);
    			
    		
    		 ObjectResult<ReporteRequerimientoBienServicioDireccionAreaDetalleExporta_Pres> TraerReporteRequerimientoBienServicioDireccionAreaDetalleExporta(Nullable<int> idDireccion, Nullable<int> anio, string tipo);
    			
    		
    		 ObjectResult<ReporteRequerimientoBienServicioDireccionAreaExporta_Pres> TraerReporteRequerimientoBienServicioDireccionAreaExporta(Nullable<int> idDireccion, Nullable<int> anio, string tipo);
    			
    		
    		 ObjectResult<Nullable<bool>> ActualizarEstadoRequerimientoForebise(Nullable<int> opcion, Nullable<int> tipo, Nullable<int> idForebise, Nullable<int> estado, string usuario, Nullable<System.DateTime> fecha);
    			
    		
    		 ObjectResult<CertificacionMasterPres> TraerListaCertificacionMaster(Nullable<int> anio);
    			
    		
    		 ObjectResult<Nullable<bool>> AnularCertificacionMaster(Nullable<int> opcion, Nullable<int> idCerMas, Nullable<int> tipoReq, string nomUsuario);
    			
    		
    		 ObjectResult<ForebisePres> TraerListaForebise(Nullable<int> opcion);
    			
    		
    		 ObjectResult<ValidarForebisePres> ValidarForebise(Nullable<int> idCerMas);
    			
    		
    		 ObjectResult<VerificaCertificacionDetallePres> VerificaCertificacionDetalle(Nullable<int> idCerReq, Nullable<int> idCerDet);
    			
    		
    		 ObjectResult<Nullable<decimal>> TraerCantidadPendienteCertificar(Nullable<int> idForReqDet, Nullable<int> tipoReq);
    			
    		
    		 ObjectResult<CertificacionRequerimientoExportaPres> TraerListaCertificacionRequerimientoExporta(Nullable<int> tipoReq, Nullable<int> anio);
    			
    		
    		 ObjectResult<PrecioBienServicioPorGruPrePres> TraerListaPrecioBienServicioPorGruPre(Nullable<int> idGruPre, Nullable<int> anio, Nullable<int> mesIni, Nullable<int> mesFin, Nullable<int> tipoMoneda);
    			
    		
    		 int ActualizarTotalCertificacionRequerimiento(Nullable<int> idCerReq);
    			
    		
    		 ObjectResult<ReporteEjecucionPresupuestoPorCuentasPres> TraerReporteEjecucionPresupuestoPorCuentas(Nullable<int> anio, Nullable<int> idPresupuesto, Nullable<int> nivelPresupuesto, Nullable<int> nivelCuenta, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteEjecucionPresupuestoPorCuentasDetallePres> TraerReporteEjecucionPresupuestoPorCuentasDetalle(Nullable<int> anio, Nullable<int> idPresupuesto, Nullable<int> nivelPresupuesto, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<RequerimientoRecursoHumanoPres> TraerListaRequerimientoRecursoHumano(Nullable<int> anio, Nullable<int> idUsuario);
    			
    		
    		 ObjectResult<Nullable<bool>> AnularRequerimientoRecursoHumano(Nullable<int> idReqRecHum, string nomUsuario);
    			
    		
    		 ObjectResult<RequerimientoRecursoHumanoDetallePres> TraerListaRequerimientoRecursoHumanoDetalle(Nullable<int> idReqRecHum);
    			
    		
    		 ObjectResult<PrecioBienServicioPres> TraerListaPrecioBienServicioRequerimiento(Nullable<int> anio, Nullable<int> idProducto, Nullable<int> idCueCon, Nullable<int> idReqBieSer, Nullable<int> tipo);
    			
    		
    		 ObjectResult<ReporteRequerimientoRRHHPres> TraerReporteRequerimientoRRHH(Nullable<int> anio, Nullable<int> idDireccion, Nullable<int> idReqRecHum);
    			
    		
    		 ObjectResult<ReporteRequerimientoBienServicioDetalleExportaPres> TraerReporteRequerimientoBienServicioDetalleExporta(Nullable<int> idReqBieSer);
    			
    		
    		 ObjectResult<ReporteRequerimientoBienServicioExportaPres> TraerReporteRequerimientoBienServicioExporta(Nullable<int> idReqBieSer);
    			
    		
    		 ObjectResult<ProgramacionAnualDetallePorMesPres> TraerListaProgramacionAnualDetallePorMes(Nullable<int> idProAnu, Nullable<int> mes, Nullable<int> idSubpresupuesto);
    			
    		
    		 ObjectResult<ReajusteMensualDetallePorMesPres> TraerListaReajusteMensualDetallePorMes(Nullable<int> idReaMenPro, Nullable<int> mes, Nullable<int> idSubpresupuesto);
    			
    		
    		 ObjectResult<ReporteCertificacionOrdenProvisionPres> TraerReporteCertificacionOrdenProvision(Nullable<int> anio, Nullable<int> mes, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<Nullable<bool>> AnularProgramacionAnualAreaPorCuenta(Nullable<int> idProAnu, Nullable<int> idCueCon, Nullable<int> idArea, string nomUsuario);
    			
    		
    		 ObjectResult<ReporteProgramacionAnualDetalleExportaPres> TraerReporteProgramacionAnualDetalleExporta(Nullable<int> idProAnu, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteProgramacionAnualExportaPres> TraerReporteProgramacionAnualExporta(Nullable<int> idProAnu, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteSubpresupuestoDetalleExportaPres> TraerReporteSubpresupuestoDetalleExporta(Nullable<int> idSubPresupuesto, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteSubpresupuestoExportaPres> TraerReporteSubpresupuestoExporta(Nullable<int> idSubPresupuesto, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteReajusteMensualDetalleExportaPres> TraerReporteReajusteMensualDetalleExporta(Nullable<int> idReaMenPro, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteReajusteMensualExportaPres> TraerReporteReajusteMensualExporta(Nullable<int> idReaMenPro, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteEvaluacionReajusteMensualDetalleExportaPres> TraerReporteEvaluacionReajusteMensualDetalleExporta(Nullable<int> idProAnu, Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteEvaluacionReajusteMensualExportaPres> TraerReporteEvaluacionReajusteMensualExporta(Nullable<int> idProAnu, Nullable<int> anio, Nullable<int> mesRea, Nullable<int> mesEva, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteEvaluacionMensualDetalleExportaPres> TraerReporteEvaluacionMensualDetalleExporta(Nullable<int> idEvaMenPro, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteEvaluacionMensualExportaPres> TraerReporteEvaluacionMensualExporta(Nullable<int> idEvaMenPro, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<PlanAnualAdquisicionReqPres> TraerListaPlanAnualAdquisicionReq(Nullable<int> idPaa);
    			
    		
    		 ObjectResult<PlanAnualAdquisicionReqDetallePres> TraerListaPlanAnualAdquisicionReqDetalle(Nullable<int> idPaaReq);
    			
    		
    		 ObjectResult<ImporteMinCerPres> TraerImporteMinCer();
    			
    		
    		 ObjectResult<SubPresupuestoPocoPres> BuscarSubPresupuestoPoco(Nullable<int> idSubpresupuesto);
    			
    		
    		 ObjectResult<UsuarioCorreoPres> TraerListaUsuarioCorreo();
    			
    		
    		 ObjectResult<ReporteCertificacionPresupuestalPres> TraerReporteCertificacionPresupuestalVarios(string idsCerReq, Nullable<bool> esAmpliacion);
    			
    		
    		 ObjectResult<VerificaSubpresupuestoPres> VerificarSubpresupuesto(Nullable<int> idSubpresupuesto);
    			
    		
    		 ObjectResult<RequerimientoRecursoHumanoPres> BuscarRequerimientoRecursoHumano(Nullable<int> idReqRecHum);
    			
    		
    		 ObjectResult<ReporteRequerimientoRRHHPres> TraerReporteRequerimientoRRHHDireccionArea(Nullable<int> anio, Nullable<int> idDireccion, Nullable<int> idSubdireccion, Nullable<int> idReqRecHum);
    			
    		
    		 ObjectResult<ReporteRequerimientoBienServicioDetalleMensualPres> TraerReporteRequerimientoBienServicioDetalleMensual(Nullable<int> idReqBieSer);
    			
    		
    		 ObjectResult<ReporteProgramacionAnualGenericaGastosPres> TraerReporteProgramacionAnualGenericaGastos(string codigos, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteProgramacionAnualDetalleExportaMasivoPres> TraerReporteProgramacionAnualDetalleExportaMasivo(string codigos, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteProgramacionAnualExportaMasivoPres> TraerReporteProgramacionAnualExportaMasivo(string codigos, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReportePresupuestoFasesPres> TraerReportePresupuestoFases(Nullable<int> anio, Nullable<int> idMoneda, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> idPresupuesto, Nullable<int> nivelPresupuesto);
    			
    		
    		 ObjectResult<PartidaPresupuestalPres> TraerListaPartidaPresupuestal();
    			
    		
    		 ObjectResult<PartidaPresupuestalPrecioPres> TraerPartidaPresupuestalPrecio(Nullable<int> tipo, string descripcion, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ProductoPrecioPres> TraerProductoPrecio(string descripcion, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<RequerimientoMensualBienServicioPres> TraerListaRequerimientoMensualBienServicio(Nullable<int> anio, Nullable<int> mes, Nullable<int> idUsuario, Nullable<int> idPresupuesto, Nullable<bool> listarTodos);
    			
    		
    		 ObjectResult<RequerimientoMensualDetallePres> TraerListaRequerimientoMensualDetalle(Nullable<int> idReqMenBieSer);
    			
    		
    		 ObjectResult<RequerimientoMensualDetallePres> TraerListaRequerimientoMensualDetalleDireccion(Nullable<int> idDirección, Nullable<int> idSubdireccion, string tipo, Nullable<int> idTipoRequerimiento, Nullable<int> anio, Nullable<int> mes);
    			
    		
    		 ObjectResult<OpcionMenuSistemaUsuarioPres> TraerOpcionPorMenuSistemaUsuario(Nullable<int> idUsuario, Nullable<int> idSistema, Nullable<int> idMenu);
    			
    		
    		 int GuardarDetalleRequerimientoMensualEnReajuste(Nullable<int> idReaMenPro, string usuario);
    			
    		
    		 ObjectResult<ReporteEvaluacionMensualExportaGenericaPres> TraerReporteEvaluacionMensualExportaGenerica(Nullable<int> idEvaMenPro, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReportePresupuestoEjecutadoPres> TraerReportePresupuestoEjecutado(Nullable<int> idMoneda, Nullable<int> anio, Nullable<int> mesInicio, Nullable<int> mesFin, string numCuenta);
    			
    		
    		 ObjectResult<ReporteEvaluacionPresupuestoPorCuentasPres> TraerReporteEvaluacionPresupuestoPorCuentas(Nullable<int> idMoneda, Nullable<int> anio, Nullable<int> idPresupuesto, Nullable<int> nivelPresupuesto);
    			
    		
    		 ObjectResult<ReporteEvaluacionPresupuestoPorCuentasDetallePres> TraerReporteEvaluacionPresupuestoPorCuentasDetalle(Nullable<int> idMoneda, Nullable<int> anio, Nullable<int> idPresupuesto, Nullable<int> nivelPresupuesto);
    			
    		
    		 ObjectResult<ReporteRequerimientoMensualSeguimientoPres> TraerReporteRequerimientoMensualSeguimiento(Nullable<int> idReqMenBieSer, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteRequerimientoMensualSeguimientoDetallePres> TraerReporteRequerimientoMensualSeguimientoDetalle(Nullable<int> idReqMenBieSer, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteRequerimientoMensualSeguimientoForebisePres> TraerReporteRequerimientoMensualSeguimientoForebise(Nullable<int> idReqMenBieSer, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ReporteRequerimientoMensualSeguimientoDetalleForebisePres> TraerReporteRequerimientoMensualSeguimientoDetalleForebise(Nullable<int> idReqMenBieSer, Nullable<int> idMoneda);
    			
    		
    		 ObjectResult<ProductoPartidaPres> TraerProductoPartida(Nullable<int> tipo, Nullable<int> idProPar);
    			
    		
    		 int GuardarDetalleRequerimientoAnualBienesServiciosToClonar(Nullable<int> idReqBieSer, Nullable<int> idReqBieSerOrigen, string usuario, ObjectParameter resultado);
    			
    		
    		 int GuardarDetalleRequerimientoMensualBienesServiciosToClonar(Nullable<int> idReqMenBieSer, Nullable<int> idReqMenBieSerOrigen, string usuario, ObjectParameter resultado);
    			
    		
    		 ObjectResult<PuestoRequerimientoAnualPres> TraerListaPuestoRequerimientoAnual(Nullable<int> anio);
    			
    		
    		 int GuardarPuestoRequerimientoEnProgramacionAnual(string codigos, Nullable<int> idProAnu, string usuario, ObjectParameter resultado);
    			
    		
    		 ObjectResult<RequerimientoBienServicio> TraerListaRequerimientoBienServicioPorArea(Nullable<int> tipo, Nullable<int> anio, Nullable<int> mes, Nullable<int> idArea);
    			
    		
    		 ObjectResult<RequerimientoBienServicio> TraerListaRequerimientoBienServicioPorArea(Nullable<int> tipo, Nullable<int> anio, Nullable<int> mes, Nullable<int> idArea, MergeOption mergeOption);
    			
    		
    		 ObjectResult<ValidaFechaCertificacionPres> ValidaFechaCertificacion(Nullable<System.DateTime> fechaEmision, Nullable<int> numero, string opcion, Nullable<int> idCerReq);
    			
    		
    		 ObjectResult<Nullable<bool>> ActualizarEstadoCertificacionPresupuestal(Nullable<int> idCerReq, string opcion, string usuario);
    			
    		
    		 ObjectResult<Nullable<decimal>> TraerImporteCotizacionPorCertificacion(Nullable<int> idCerReq);
    			
    		
    		 ObjectResult<Nullable<bool>> ActualizarImporteCertificacion(Nullable<int> idCerReq, string usuario);
    			
    		
    		 ObjectResult<OrdenPorCertificacionPres> TraerListaOrdenPorCertificacion(Nullable<int> idCerReq);
    			
    		
    		 int GuardarDetalleReqMensualBienServicioDesdeReqAnual(Nullable<int> idReqMenBieSer, Nullable<int> tipo, Nullable<int> mes, string idsReqBieSer, string usuario, ObjectParameter resultado);
    			
    		
    		 ObjectResult<ReporteRequerimientoRRHHDireccionImportePres> TraerReporteRequerimientoRRHHDireccionImporte(Nullable<int> anio, Nullable<int> idDireccion, Nullable<int> idSubdireccion, Nullable<int> idReqRecHum, Nullable<int> idMoneda);
    			
    		
    		 int GuardarDetalleProgramacionAnualDesdeRequerimientoAnual(Nullable<int> idProAnu, string idsReqBieSer, string usuario);
    			
    		
    }
}
