//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.WinForm.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIA_Presupuesto.WinForm.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string Abrir {
            get {
                return ResourceManager.GetString("Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cerrarán todos los modulos abiertos. ¿Deseas continuar?.
        /// </summary>
        internal static string AdvertenciaCierreModulos {
            get {
                return ResourceManager.GetString("AdvertenciaCierreModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y clave incorrectas. Por favor intente escribir nuevamente..
        /// </summary>
        internal static string CredencialesInvalidas {
            get {
                return ResourceManager.GetString("CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo no es válido. Debe ser registrado primero..
        /// </summary>
        internal static string PeriodoNoValido {
            get {
                return ResourceManager.GetString("PeriodoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        internal static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted no aceptó el periodo y se tomará el periodo de la fecha actual. ¿Usted esta seguro?.
        /// </summary>
        internal static string PreguntaPeriodoNoAceptado {
            get {
                return ResourceManager.GetString("PreguntaPeriodoNoAceptado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de Credenciales de Usuario.
        /// </summary>
        internal static string ValidacionUsuario {
            get {
                return ResourceManager.GetString("ValidacionUsuario", resourceCulture);
            }
        }
    }
}
