//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIA_Presupuesto.Negocio.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Anular Registro {0}.
        /// </summary>
        internal static string ErrorDeAnulacion {
            get {
                return ResourceManager.GetString("ErrorDeAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Crear Registro {0}.
        /// </summary>
        internal static string ErrorDeCreacion {
            get {
                return ResourceManager.GetString("ErrorDeCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Eliminar Registro {0}.
        /// </summary>
        internal static string ErrorDeEliminacion {
            get {
                return ResourceManager.GetString("ErrorDeEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al  Modificar Registro {0}.
        /// </summary>
        internal static string ErrorDeModificacion {
            get {
                return ResourceManager.GetString("ErrorDeModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se anuló correctamente {0} : {1}.
        /// </summary>
        internal static string MensajeAnulacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeAnulacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ingresó correctamente {0} : {1}.
        /// </summary>
        internal static string MensajeCreacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeCreacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Eliminó correctamente {0} : {1}.
        /// </summary>
        internal static string MensajeElimininacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeElimininacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio el siguiente error: {0}, El seguimiento es el siguiente: {1} .
        /// </summary>
        internal static string MensajeError {
            get {
                return ResourceManager.GetString("MensajeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ocurrido un error  al ordenar la estructura para el procesamiento de la planilla. {0}.
        /// </summary>
        internal static string MensajeErrorOrdenamientoEstructura {
            get {
                return ResourceManager.GetString("MensajeErrorOrdenamientoEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizó correctamente {0} : {1}.
        /// </summary>
        internal static string MensajeModificacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeModificacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro no reconocido &quot;{0}&quot;..
        /// </summary>
        internal static string MensajeParametroNoReconocido {
            get {
                return ResourceManager.GetString("MensajeParametroNoReconocido", resourceCulture);
            }
        }
    }
}
