//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.WinForm.General.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIA_Presupuesto.WinForm.General.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string Abrir {
            get {
                return ResourceManager.GetString("Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cerrarán todos los modulos abiertos. ¿Deseas continuar?.
        /// </summary>
        internal static string AdvertenciaCierreModulos {
            get {
                return ResourceManager.GetString("AdvertenciaCierreModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo seleccionado no está registrado.
        /// </summary>
        internal static string AdvertenciaPeriodoNoExiste {
            get {
                return ResourceManager.GetString("AdvertenciaPeriodoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha ingresada no es válida..
        /// </summary>
        internal static string AdvertenciaValidacionEsFecha {
            get {
                return ResourceManager.GetString("AdvertenciaValidacionEsFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este dato es requerido..
        /// </summary>
        internal static string AdvertenciaValidacionEsNoVacio {
            get {
                return ResourceManager.GetString("AdvertenciaValidacionEsNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dato debe ser mayor que cero.
        /// </summary>
        internal static string AdvertenciaValidacionMayorCero {
            get {
                return ResourceManager.GetString("AdvertenciaValidacionMayorCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este dato debe ser mayor o igual a cero..
        /// </summary>
        internal static string AdvertenciaValidacionMayorIgualCero {
            get {
                return ResourceManager.GetString("AdvertenciaValidacionMayorIgualCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de anular el registro: {0}?.
        /// </summary>
        internal static string AnularRegistro {
            get {
                return ResourceManager.GetString("AnularRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a HTML (Página Web).
        /// </summary>
        internal static string BotonExportaHTML {
            get {
                return ResourceManager.GetString("BotonExportaHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a Imagen.
        /// </summary>
        internal static string BotonExportaImagen {
            get {
                return ResourceManager.GetString("BotonExportaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a MHT.
        /// </summary>
        internal static string BotonExportaMHT {
            get {
                return ResourceManager.GetString("BotonExportaMHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a PDF.
        /// </summary>
        internal static string BotonExportaPDF {
            get {
                return ResourceManager.GetString("BotonExportaPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a  RTF.
        /// </summary>
        internal static string BotonExportaRTF {
            get {
                return ResourceManager.GetString("BotonExportaRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a texto.
        /// </summary>
        internal static string BotonExportaTXT {
            get {
                return ResourceManager.GetString("BotonExportaTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a XLS (Excel 2003).
        /// </summary>
        internal static string BotonExportaXLS {
            get {
                return ResourceManager.GetString("BotonExportaXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a XLSX (Excel 2007 y 2010).
        /// </summary>
        internal static string BotonExportaXLSX {
            get {
                return ResourceManager.GetString("BotonExportaXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exporta a XML.
        /// </summary>
        internal static string BotonExportaXML {
            get {
                return ResourceManager.GetString("BotonExportaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere mientras cargan los datos....
        /// </summary>
        internal static string CargaDatos {
            get {
                return ResourceManager.GetString("CargaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Usted quiere guardar los cambios realizados?.
        /// </summary>
        internal static string CerrarFormularioAdvertenciaCancelar {
            get {
                return ResourceManager.GetString("CerrarFormularioAdvertenciaCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de abandonar la sesión?.
        /// </summary>
        internal static string CerrarMDIFormularioAdvertencia {
            get {
                return ResourceManager.GetString("CerrarMDIFormularioAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y clave incorrectas. Por favor intente escribir nuevamente..
        /// </summary>
        internal static string CredencialesInvalidas {
            get {
                return ResourceManager.GetString("CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el registro: {0}?.
        /// </summary>
        internal static string EliminarRegistro {
            get {
                return ResourceManager.GetString("EliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar exportar.
        /// </summary>
        internal static string ErrorExportar {
            get {
                return ResourceManager.GetString("ErrorExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento HTML (*.html)|*.html.
        /// </summary>
        internal static string FiltroHTMLAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroHTMLAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento MHT (*.mht)|*.mht.
        /// </summary>
        internal static string FiltroMHTAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroMHTAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento PDF  (*.pdf)|*.pdf.
        /// </summary>
        internal static string FiltroPDFAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroPDFAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento RTF (*.rtf)|*.rtf.
        /// </summary>
        internal static string FiltroRTFAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroRTFAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo plano (*.txt)|*.txt.
        /// </summary>
        internal static string FiltroTXTAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroTXTAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento XLS (*.xls)|*.xls.
        /// </summary>
        internal static string FiltroXLSAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroXLSAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento XLSX (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string FiltroXLSXAbrirArchivo {
            get {
                return ResourceManager.GetString("FiltroXLSXAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración .
        /// </summary>
        internal static string NuevoConfiguracion {
            get {
                return ResourceManager.GetString("NuevoConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        internal static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Usted desea abrir el archivo?.
        /// </summary>
        internal static string PreguntaAbrirArchivo {
            get {
                return ResourceManager.GetString("PreguntaAbrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted no aceptó el periodo y se tomará el periodo de la fecha actual. ¿Usted esta seguro?.
        /// </summary>
        internal static string PreguntaPeriodoNoAceptado {
            get {
                return ResourceManager.GetString("PreguntaPeriodoNoAceptado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Solo Lectura).
        /// </summary>
        internal static string SoloLecturaCebecera {
            get {
                return ResourceManager.GetString("SoloLecturaCebecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de Credenciales de Usuario.
        /// </summary>
        internal static string ValidacionUsuario {
            get {
                return ResourceManager.GetString("ValidacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede realizar ésta acción. El periodo está cerrado..
        /// </summary>
        internal static string ValidarPeriodoCerrado {
            get {
                return ResourceManager.GetString("ValidarPeriodoCerrado", resourceCulture);
            }
        }
    }
}
