//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.WinForm.Mantenimiento.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIA_Presupuesto.WinForm.Mantenimiento.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se activó correctamente.
        /// </summary>
        internal static string MensajeActivarSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeActivarSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se anuló correctamente.
        /// </summary>
        internal static string MensajeAnulacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeAnulacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se cerró correctamente.
        /// </summary>
        internal static string MensajeCerrarSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeCerrarSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento se eliminó correctamente.
        /// </summary>
        internal static string MensajeEliminacionDocumentoSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeEliminacionDocumentoSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se eliminó correctamente.
        /// </summary>
        internal static string MensajeEliminacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeEliminacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al activar el registro.
        /// </summary>
        internal static string MensajeErrorActivarRegistro {
            get {
                return ResourceManager.GetString("MensajeErrorActivarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al anular el registro.
        /// </summary>
        internal static string MensajeErrorAnulacion {
            get {
                return ResourceManager.GetString("MensajeErrorAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al cerrar el registro.
        /// </summary>
        internal static string MensajeErrorCerrarRegistro {
            get {
                return ResourceManager.GetString("MensajeErrorCerrarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al eliminar el registro.
        /// </summary>
        internal static string MensajeErrorEliminacion {
            get {
                return ResourceManager.GetString("MensajeErrorEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al quitar asiento contable.
        /// </summary>
        internal static string MensajeErrorQuitarAsiento {
            get {
                return ResourceManager.GetString("MensajeErrorQuitarAsiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al registrar .
        /// </summary>
        internal static string MensajeErrorRegistro {
            get {
                return ResourceManager.GetString("MensajeErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un registro.
        /// </summary>
        internal static string MensajeErrorSeleccionarOrigen {
            get {
                return ResourceManager.GetString("MensajeErrorSeleccionarOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se modificó correctamente.
        /// </summary>
        internal static string MensajeModificacionSatisfactoria {
            get {
                return ResourceManager.GetString("MensajeModificacionSatisfactoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el registro. El registro tiene un estado que no permite la modificación..
        /// </summary>
        internal static string MensajeNoModificable {
            get {
                return ResourceManager.GetString("MensajeNoModificable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asiento contable quitado correctamente.
        /// </summary>
        internal static string MensajeQuitarAsientoSatisfactorio {
            get {
                return ResourceManager.GetString("MensajeQuitarAsientoSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de documento quitado correctamente.
        /// </summary>
        internal static string MensajeQuitarDetalleSatisfactorio {
            get {
                return ResourceManager.GetString("MensajeQuitarDetalleSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se registro correctamente.
        /// </summary>
        internal static string MensajeRegistroSatisfactorio {
            get {
                return ResourceManager.GetString("MensajeRegistroSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro en activar el registro?.
        /// </summary>
        internal static string PreguntaActivarRegistro {
            get {
                return ResourceManager.GetString("PreguntaActivarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de actulizar los detalles?.
        /// </summary>
        internal static string PreguntaActulizarDetalles {
            get {
                return ResourceManager.GetString("PreguntaActulizarDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de anular el registro?.
        /// </summary>
        internal static string PreguntaAnularRegistro {
            get {
                return ResourceManager.GetString("PreguntaAnularRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro en cerrar el registro?.
        /// </summary>
        internal static string PreguntaCerrarRegistro {
            get {
                return ResourceManager.GetString("PreguntaCerrarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el registro?.
        /// </summary>
        internal static string PreguntaEliminarRegistro {
            get {
                return ResourceManager.GetString("PreguntaEliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un registro correcto.
        /// </summary>
        internal static string RegistroVacio {
            get {
                return ResourceManager.GetString("RegistroVacio", resourceCulture);
            }
        }
    }
}
