//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Area
    {
    	[DataMember]
        public int idArea { get; set; }
    	[DataMember]
        public int idSubDireccion { get; set; }
    	[DataMember]
        public string codArea { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public Nullable<byte> estado { get; set; }
    }
}
