//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class CalendarioEvaluacionyAjusteAnual
    {
    	[DataMember]
        public string codGrupo { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<decimal> enero { get; set; }
    	[DataMember]
        public Nullable<decimal> febrero { get; set; }
    	[DataMember]
        public Nullable<decimal> marzo { get; set; }
    	[DataMember]
        public Nullable<decimal> abril { get; set; }
    	[DataMember]
        public Nullable<decimal> mayo { get; set; }
    	[DataMember]
        public Nullable<decimal> junio { get; set; }
    	[DataMember]
        public Nullable<decimal> julio { get; set; }
    	[DataMember]
        public Nullable<decimal> agosto { get; set; }
    	[DataMember]
        public Nullable<decimal> setiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> octubre { get; set; }
    	[DataMember]
        public Nullable<decimal> noviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> diciembre { get; set; }
    	[DataMember]
        public Nullable<decimal> total { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public Nullable<int> mesAjuste { get; set; }
    	[DataMember]
        public Nullable<int> mesEval { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string tituloMon { get; set; }
    	[DataMember]
        public Nullable<decimal> eneroDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> eneroSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> eneroOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> febreroDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> febreroSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> febreroOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> marzoDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> marzoSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> marzoOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> abrilDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> abrilSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> abrilOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> mayoDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> mayoSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> mayoOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> junioDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> junioSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> junioOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> julioDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> julioSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> julioOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> agostoDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> agostoSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> agostoOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> setiembreDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> setiembreSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> setiembreOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> octubreDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> octubreSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> octubreOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> noviembreDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> noviembreSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> noviembreOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> diciembreDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> diciembreSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> diciembreOtros { get; set; }
    }
}
