//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.PuestoReajustePresupuesto = new HashSet<PuestoReajustePresupuesto>();
            this.PuestoPresupuesto = new HashSet<PuestoPresupuesto>();
        }
    
    	[DataMember]
        public int idCargo { get; set; }
    	[DataMember]
        public int idOcupacion { get; set; }
    	[DataMember]
        public int idDireccion { get; set; }
    	[DataMember]
        public string codCargo { get; set; }
    	[DataMember]
        public string desCargo { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public bool estado { get; set; }
    	[DataMember]
        public Nullable<int> formatoIPERC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PuestoReajustePresupuesto> PuestoReajustePresupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PuestoPresupuesto> PuestoPresupuesto { get; set; }
    }
}
