//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class CargoPres
    {
    	[DataMember]
        public int idCargo { get; set; }
    	[DataMember]
        public string codCargo { get; set; }
    	[DataMember]
        public string desCargo { get; set; }
    	[DataMember]
        public string direccion { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaCrea { get; set; }
    	[DataMember]
        public int grado { get; set; }
    	[DataMember]
        public decimal remuneracion { get; set; }
    	[DataMember]
        public int idMoneda { get; set; }
    	[DataMember]
        public string desMoneda { get; set; }
    }
}
