//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class CertificacionDetallePres
    {
    	[DataMember]
        public Nullable<int> idCerDet { get; set; }
    	[DataMember]
        public Nullable<int> idForeDet { get; set; }
    	[DataMember]
        public Nullable<int> idFore { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string direccion { get; set; }
    	[DataMember]
        public string subdireccion { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public Nullable<int> idReaMenDet { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> tipoDet { get; set; }
    	[DataMember]
        public Nullable<decimal> subTotal { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public Nullable<int> idCerMas { get; set; }
    	[DataMember]
        public Nullable<int> idCerReq { get; set; }
    	[DataMember]
        public Nullable<decimal> cantPendiente { get; set; }
    	[DataMember]
        public Nullable<bool> esAmpliacion { get; set; }
    	[DataMember]
        public string desAmpliacion { get; set; }
    }
}
