//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class CertificacionRequerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificacionRequerimiento()
        {
            this.CertificacionDetalle = new HashSet<CertificacionDetalle>();
            this.CertificacionRequerimientoSubprespuesto = new HashSet<CertificacionRequerimientoSubprespuesto>();
        }
    
    	[DataMember]
        public int idCerReq { get; set; }
    	[DataMember]
        public int numero { get; set; }
    	[DataMember]
        public string sigla { get; set; }
    	[DataMember]
        public System.DateTime fechaEmision { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> nivelPresupuesto { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public Nullable<int> idCerMas { get; set; }
    	[DataMember]
        public string observacion { get; set; }
    	[DataMember]
        public Nullable<decimal> totalSoles { get; set; }
    	[DataMember]
        public Nullable<decimal> totalDolares { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public string usuAmp { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaAmp { get; set; }
    	[DataMember]
        public string usuEditaAmp { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEditaAmp { get; set; }
    	[DataMember]
        public string justificacionAmp { get; set; }
    	[DataMember]
        public string detalle { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<CertificacionDetalle> CertificacionDetalle { get; set; }
        public virtual CertificacionMaster CertificacionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<CertificacionRequerimientoSubprespuesto> CertificacionRequerimientoSubprespuesto { get; set; }
    }
}
