//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ConceptoPresupuestoRemuneracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConceptoPresupuestoRemuneracion()
        {
            this.ConceptoCuentaContable = new HashSet<ConceptoCuentaContable>();
            this.ParametroPresupuestoRemuneracion = new HashSet<ParametroPresupuestoRemuneracion>();
            this.PropiedadPresupuestoRemuneracion = new HashSet<PropiedadPresupuestoRemuneracion>();
        }
    
    	[DataMember]
        public int idConPreRem { get; set; }
    	[DataMember]
        public Nullable<int> idOriCon { get; set; }
    	[DataMember]
        public string tipo { get; set; }
    	[DataMember]
        public string codigo { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string abreviatura { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ConceptoCuentaContable> ConceptoCuentaContable { get; set; }
        public virtual OrigenConcepto OrigenConcepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ParametroPresupuestoRemuneracion> ParametroPresupuestoRemuneracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PropiedadPresupuestoRemuneracion> PropiedadPresupuestoRemuneracion { get; set; }
    }
}
