//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ConsolidadoPresupuesto
    {
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<decimal> DA { get; set; }
    	[DataMember]
        public Nullable<decimal> DI { get; set; }
    	[DataMember]
        public Nullable<decimal> DO { get; set; }
    	[DataMember]
        public Nullable<decimal> DE { get; set; }
    	[DataMember]
        public Nullable<decimal> ERR { get; set; }
    	[DataMember]
        public decimal CAN_DA { get; set; }
    	[DataMember]
        public decimal CAN_DI { get; set; }
    	[DataMember]
        public decimal CAN_DO { get; set; }
    	[DataMember]
        public decimal CAN_DE { get; set; }
    	[DataMember]
        public decimal CAN_ERR { get; set; }
    	[DataMember]
        public Nullable<int> HEC { get; set; }
    	[DataMember]
        public string codGrupo { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string tituloMon { get; set; }
    	[DataMember]
        public Nullable<decimal> total { get; set; }
    	[DataMember]
        public Nullable<decimal> DADevida { get; set; }
    	[DataMember]
        public Nullable<decimal> DASaal { get; set; }
    	[DataMember]
        public Nullable<decimal> DAOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> DIDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> DISaal { get; set; }
    	[DataMember]
        public Nullable<decimal> DIOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> DODevida { get; set; }
    	[DataMember]
        public Nullable<decimal> DOSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> DOOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> DEDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> DESaal { get; set; }
    	[DataMember]
        public Nullable<decimal> DEOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> ERRDevida { get; set; }
    	[DataMember]
        public Nullable<decimal> ERRSaal { get; set; }
    	[DataMember]
        public Nullable<decimal> ERROtros { get; set; }
    	[DataMember]
        public Nullable<decimal> Devida { get; set; }
    	[DataMember]
        public Nullable<decimal> Saal { get; set; }
    	[DataMember]
        public Nullable<decimal> Otros { get; set; }
    	[DataMember]
        public string tituloTotal { get; set; }
    	[DataMember]
        public string tituloSaal { get; set; }
    	[DataMember]
        public string tituloDevida { get; set; }
    	[DataMember]
        public string tituloOtros { get; set; }
    }
}
