//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class CuentaContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaContable()
        {
            this.CuentaContable1 = new HashSet<CuentaContable>();
            this.GrupoCuentaDetalle = new HashSet<GrupoCuentaDetalle>();
            this.ProgramacionAnualArea = new HashSet<ProgramacionAnualArea>();
            this.EvaluacionMensualArea = new HashSet<EvaluacionMensualArea>();
            this.CertificacionDetalle = new HashSet<CertificacionDetalle>();
            this.RequerimientoBienServicioDetalle = new HashSet<RequerimientoBienServicioDetalle>();
            this.RequerimientoMensualDetalle = new HashSet<RequerimientoMensualDetalle>();
            this.PartidaPresupuestalCuenta = new HashSet<PartidaPresupuestalCuenta>();
        }
    
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<int> idPlaCue { get; set; }
    	[DataMember]
        public string abreviatura { get; set; }
    	[DataMember]
        public string abreviaturaliq { get; set; }
    	[DataMember]
        public Nullable<int> idTipCtaCon { get; set; }
    	[DataMember]
        public string DeudorAcreedor { get; set; }
    	[DataMember]
        public string anexoPrincipal { get; set; }
    	[DataMember]
        public string anexoSecundario { get; set; }
    	[DataMember]
        public Nullable<int> idNivSal { get; set; }
    	[DataMember]
        public Nullable<bool> inConBan { get; set; }
    	[DataMember]
        public Nullable<bool> esManual { get; set; }
    	[DataMember]
        public Nullable<int> dependencia { get; set; }
    	[DataMember]
        public Nullable<int> nivel { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fecCrea { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fecEdita { get; set; }
    	[DataMember]
        public Nullable<int> idCatCon { get; set; }
    	[DataMember]
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<CuentaContable> CuentaContable1 { get; set; }
        public virtual CuentaContable CuentaContable2 { get; set; }
        public virtual PlanCuenta PlanCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<GrupoCuentaDetalle> GrupoCuentaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualArea> ProgramacionAnualArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<EvaluacionMensualArea> EvaluacionMensualArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<CertificacionDetalle> CertificacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoBienServicioDetalle> RequerimientoBienServicioDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoMensualDetalle> RequerimientoMensualDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PartidaPresupuestalCuenta> PartidaPresupuestalCuenta { get; set; }
    }
}
