//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class DatoConceptoCuentaContable
    {
    	[DataMember]
        public int idConCueCon { get; set; }
    	[DataMember]
        public string concepto { get; set; }
    	[DataMember]
        public string regimen { get; set; }
    	[DataMember]
        public string categoria { get; set; }
    	[DataMember]
        public string condicion { get; set; }
    	[DataMember]
        public string numcuenta { get; set; }
    }
}
