//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class DatoCalculoPresupuestoRemuneracion
    {
    	[DataMember]
        public int idPuePre { get; set; }
    	[DataMember]
        public Nullable<int> idTrabajador { get; set; }
    	[DataMember]
        public int idProPreRem { get; set; }
    	[DataMember]
        public int idConPreRem { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    }
}
