//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class DatosPuestoCalculo
    {
    	[DataMember]
        public int idTrabajador { get; set; }
    	[DataMember]
        public string trabajador { get; set; }
    	[DataMember]
        public decimal remuneracion { get; set; }
    	[DataMember]
        public int grado { get; set; }
    	[DataMember]
        public Nullable<bool> esRemDiaria { get; set; }
    	[DataMember]
        public int idCargo { get; set; }
    	[DataMember]
        public Nullable<int> idSede { get; set; }
    	[DataMember]
        public int idTipMon { get; set; }
    	[DataMember]
        public string nroDocIdentidad { get; set; }
    	[DataMember]
        public int idRegLab { get; set; }
    	[DataMember]
        public int idConLab { get; set; }
    	[DataMember]
        public int idCatLab { get; set; }
    	[DataMember]
        public Nullable<bool> conBonoAlimento { get; set; }
    	[DataMember]
        public Nullable<bool> conBonoAlimentoAdi { get; set; }
    	[DataMember]
        public Nullable<bool> conBonoMovilidad { get; set; }
    	[DataMember]
        public Nullable<bool> conBonoProductividad { get; set; }
    	[DataMember]
        public int idAreLab { get; set; }
    }
}
