//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class EvaluacionMensualProgramacionArea
    {
    	[DataMember]
        public int idEvaMenProArea { get; set; }
    	[DataMember]
        public Nullable<int> idEvaMenArea { get; set; }
    	[DataMember]
        public Nullable<int> idProAnuArea { get; set; }
    
        public virtual ProgramacionAnualArea ProgramacionAnualArea { get; set; }
        public virtual EvaluacionMensualArea EvaluacionMensualArea { get; set; }
    }
}
