//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class EvaluacionMensualArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionMensualArea()
        {
            this.EvaluacionMensualAreaMes = new HashSet<EvaluacionMensualAreaMes>();
            this.EvaluacionMensualDetalle = new HashSet<EvaluacionMensualDetalle>();
            this.EvaluacionMensualProgramacionArea = new HashSet<EvaluacionMensualProgramacionArea>();
        }
    
    	[DataMember]
        public int idEvaMenArea { get; set; }
    	[DataMember]
        public int idEvaMenPro { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public int idArea { get; set; }
    	[DataMember]
        public Nullable<int> idUnidad { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual EvaluacionMensualProgramacion EvaluacionMensualProgramacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<EvaluacionMensualAreaMes> EvaluacionMensualAreaMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<EvaluacionMensualDetalle> EvaluacionMensualDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<EvaluacionMensualProgramacionArea> EvaluacionMensualProgramacionArea { get; set; }
    }
}
