//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class EvaluacionPresupuestoDetalleMovimientosPres
    {
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string voucher { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMov { get; set; }
    	[DataMember]
        public string glosa { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    }
}
