//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class EvaluacionMensualProgramacionPres
    {
    	[DataMember]
        public int idEvaMenProPres { get; set; }
    	[DataMember]
        public int idEvaMenPro { get; set; }
    	[DataMember]
        public int idPresupuesto { get; set; }
    	[DataMember]
        public int nivelPresupuesto { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual EvaluacionMensualProgramacion EvaluacionMensualProgramacion { get; set; }
    }
}
