//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ForebisePres
    {
    	[DataMember]
        public int dcid { get; set; }
    	[DataMember]
        public string codigo { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idSubPresupuesto { get; set; }
    	[DataMember]
        public string desGruPresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public string desSubPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idDireccion { get; set; }
    	[DataMember]
        public Nullable<int> idSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string desSubDireccion { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public Nullable<int> estado { get; set; }
    	[DataMember]
        public Nullable<int> estadoAD { get; set; }
    	[DataMember]
        public string usuADA { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaADA { get; set; }
    	[DataMember]
        public Nullable<int> estadoCER { get; set; }
    	[DataMember]
        public string usuCER { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaCER { get; set; }
    	[DataMember]
        public Nullable<bool> esAnual { get; set; }
    }
}
