//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ForeDetallePres
    {
    	[DataMember]
        public int idDetalle { get; set; }
    	[DataMember]
        public Nullable<int> idCabecera { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public decimal subTotal { get; set; }
    }
}
