//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ForebiDetalle
    {
    	[DataMember]
        public int idForebiDet { get; set; }
    	[DataMember]
        public Nullable<int> idForebi { get; set; }
    	[DataMember]
        public Nullable<int> idProducto { get; set; }
    	[DataMember]
        public string desProducto { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<int> idUnidad { get; set; }
    	[DataMember]
        public string abrUnidad { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    }
}
