//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class GastoRecurrenteDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GastoRecurrenteDetalle()
        {
            this.GastoRecurrenteDetalleMes = new HashSet<GastoRecurrenteDetalleMes>();
        }
    
    	[DataMember]
        public int idGasRecDet { get; set; }
    	[DataMember]
        public Nullable<int> idGasRecReq { get; set; }
    	[DataMember]
        public Nullable<int> idReqBieSerDet { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public int idUnidad { get; set; }
    	[DataMember]
        public int idProducto { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public decimal subTotal { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    	[DataMember]
        public Nullable<decimal> precioOrigen { get; set; }
    
        public virtual GastoRecurrenteRequerimiento GastoRecurrenteRequerimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<GastoRecurrenteDetalleMes> GastoRecurrenteDetalleMes { get; set; }
    }
}
