//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class GastoRecurrenteDetalleMes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GastoRecurrenteDetalleMes()
        {
            this.ProgramacionAnualGastoDetalleMes = new HashSet<ProgramacionAnualGastoDetalleMes>();
        }
    
    	[DataMember]
        public int idGasRecDetMes { get; set; }
    	[DataMember]
        public int idGasRecDet { get; set; }
    	[DataMember]
        public Nullable<int> idReqBieSerDetMes { get; set; }
    	[DataMember]
        public int mes { get; set; }
    	[DataMember]
        public decimal cantidad { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual GastoRecurrenteDetalle GastoRecurrenteDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualGastoDetalleMes> ProgramacionAnualGastoDetalleMes { get; set; }
    }
}
