//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class GrupoFinanciamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoFinanciamiento()
        {
            this.GrupoFinanciamientoDetalle = new HashSet<GrupoFinanciamientoDetalle>();
            this.TipoReporteGrupoFinan = new HashSet<TipoReporteGrupoFinan>();
        }
    
    	[DataMember]
        public int idGruFin { get; set; }
    	[DataMember]
        public int idFueFin { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    
        public virtual FuenteFinanciamiento FuenteFinanciamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<GrupoFinanciamientoDetalle> GrupoFinanciamientoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<TipoReporteGrupoFinan> TipoReporteGrupoFinan { get; set; }
    }
}
