//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class GrupoPresupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoPresupuesto()
        {
            this.PresupuestoRecepcionado = new HashSet<PresupuestoRecepcionado>();
            this.TipoReporteGrupoPresupuesto = new HashSet<TipoReporteGrupoPresupuesto>();
            this.ProgramacionAnual = new HashSet<ProgramacionAnual>();
        }
    
    	[DataMember]
        public int idGruPre { get; set; }
    	[DataMember]
        public Nullable<int> idFueFin { get; set; }
    	[DataMember]
        public string codigo { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string abreviatura { get; set; }
    	[DataMember]
        public string observacion { get; set; }
    	[DataMember]
        public bool esEncargo { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual FuenteFinanciamiento FuenteFinanciamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PresupuestoRecepcionado> PresupuestoRecepcionado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<TipoReporteGrupoPresupuesto> TipoReporteGrupoPresupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnual> ProgramacionAnual { get; set; }
    }
}
