//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class OpcionMenuSistemaUsuarioPres
    {
    	[DataMember]
        public int idUsuario { get; set; }
    	[DataMember]
        public int idSistema { get; set; }
    	[DataMember]
        public string nomSistema { get; set; }
    	[DataMember]
        public int idMenu { get; set; }
    	[DataMember]
        public string nomMenu { get; set; }
    	[DataMember]
        public int idOpcion { get; set; }
    	[DataMember]
        public string nomOpcion { get; set; }
    	[DataMember]
        public bool estadoPerfil { get; set; }
    	[DataMember]
        public bool estadoMenuOpcion { get; set; }
    }
}
