//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class OrdenPorCertificacionPres
    {
    	[DataMember]
        public Nullable<int> idCerMas { get; set; }
    	[DataMember]
        public Nullable<int> idCerReq { get; set; }
    	[DataMember]
        public Nullable<int> idForebise { get; set; }
    	[DataMember]
        public Nullable<int> tipoReq { get; set; }
    	[DataMember]
        public Nullable<int> idOrden { get; set; }
    	[DataMember]
        public string numero { get; set; }
    }
}
