//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PartidaPresupuestalPres
    {
    	[DataMember]
        public int idParPre { get; set; }
    	[DataMember]
        public string tipo { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string und { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    }
}
