//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PlanAnualAdquisicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanAnualAdquisicion()
        {
            this.PlanAnualAdquisicionRequerimiento = new HashSet<PlanAnualAdquisicionRequerimiento>();
        }
    
    	[DataMember]
        public int idPaa { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
    	[DataMember]
        public int idEntidad { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public string siglas { get; set; }
    	[DataMember]
        public string uniEje { get; set; }
    	[DataMember]
        public string pliego { get; set; }
    	[DataMember]
        public string docAprobacion { get; set; }
    	[DataMember]
        public Nullable<int> idMoneda { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PlanAnualAdquisicionRequerimiento> PlanAnualAdquisicionRequerimiento { get; set; }
    }
}
