//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PlanAnualAdquisicionRequerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanAnualAdquisicionRequerimiento()
        {
            this.PlanAnualAdquisicionDetalle = new HashSet<PlanAnualAdquisicionDetalle>();
        }
    
    	[DataMember]
        public int idPaaReq { get; set; }
    	[DataMember]
        public int idPaa { get; set; }
    	[DataMember]
        public int idReqBieSer { get; set; }
    	[DataMember]
        public int idArea { get; set; }
    	[DataMember]
        public int idMoneda { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public System.DateTime fechaEmision { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual RequerimientoBienServicio RequerimientoBienServicio { get; set; }
        public virtual PlanAnualAdquisicion PlanAnualAdquisicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PlanAnualAdquisicionDetalle> PlanAnualAdquisicionDetalle { get; set; }
    }
}
