//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PlanAnualAdquisicionDetalleMes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanAnualAdquisicionDetalleMes()
        {
            this.ProgramacionAnualPlanAdqDetalleMes = new HashSet<ProgramacionAnualPlanAdqDetalleMes>();
        }
    
    	[DataMember]
        public int idPaaDetMes { get; set; }
    	[DataMember]
        public int idPaaDet { get; set; }
    	[DataMember]
        public Nullable<int> idReqBieSerDetMes { get; set; }
    	[DataMember]
        public int mes { get; set; }
    	[DataMember]
        public decimal cantidad { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual PlanAnualAdquisicionDetalle PlanAnualAdquisicionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualPlanAdqDetalleMes> ProgramacionAnualPlanAdqDetalleMes { get; set; }
    }
}
