//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PlanAnualAdquisicionDetallePres
    {
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> idPaaDet { get; set; }
    	[DataMember]
        public Nullable<int> idPaaReq { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string Abreviado { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public Nullable<decimal> enero { get; set; }
    	[DataMember]
        public Nullable<decimal> cantEnero { get; set; }
    	[DataMember]
        public Nullable<decimal> febrero { get; set; }
    	[DataMember]
        public Nullable<decimal> cantFebrero { get; set; }
    	[DataMember]
        public Nullable<decimal> marzo { get; set; }
    	[DataMember]
        public Nullable<decimal> cantMarzo { get; set; }
    	[DataMember]
        public Nullable<decimal> abril { get; set; }
    	[DataMember]
        public Nullable<decimal> cantAbril { get; set; }
    	[DataMember]
        public Nullable<decimal> mayo { get; set; }
    	[DataMember]
        public Nullable<decimal> cantMayo { get; set; }
    	[DataMember]
        public Nullable<decimal> junio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantJunio { get; set; }
    	[DataMember]
        public Nullable<decimal> julio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantJulio { get; set; }
    	[DataMember]
        public Nullable<decimal> agosto { get; set; }
    	[DataMember]
        public Nullable<decimal> cantAgosto { get; set; }
    	[DataMember]
        public Nullable<decimal> setiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantSetiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> octubre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantOctubre { get; set; }
    	[DataMember]
        public Nullable<decimal> noviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantNoviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> diciembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantDiciembre { get; set; }
    	[DataMember]
        public Nullable<decimal> total { get; set; }
    }
}
