//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PlanAnualAdquisicionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanAnualAdquisicionDetalle()
        {
            this.PlanAnualAdquisicionDetalleMes = new HashSet<PlanAnualAdquisicionDetalleMes>();
        }
    
    	[DataMember]
        public int idPaaDet { get; set; }
    	[DataMember]
        public int idPaaReq { get; set; }
    	[DataMember]
        public Nullable<int> numRef { get; set; }
    	[DataMember]
        public Nullable<bool> itemUnico { get; set; }
    	[DataMember]
        public Nullable<int> tipComSel { get; set; }
    	[DataMember]
        public string nomEnt { get; set; }
    	[DataMember]
        public Nullable<int> TipPro { get; set; }
    	[DataMember]
        public Nullable<int> objCon { get; set; }
    	[DataMember]
        public Nullable<int> nroItem { get; set; }
    	[DataMember]
        public Nullable<bool> antecedente { get; set; }
    	[DataMember]
        public string desAntecedente { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<int> idReqBieSerDet { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public Nullable<int> idUnidad { get; set; }
    	[DataMember]
        public Nullable<int> idProducto { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public Nullable<decimal> subtotal { get; set; }
    	[DataMember]
        public Nullable<int> idTipMon { get; set; }
    	[DataMember]
        public Nullable<decimal> tipCam { get; set; }
    	[DataMember]
        public Nullable<decimal> valorEst { get; set; }
    	[DataMember]
        public Nullable<int> idUbigeo { get; set; }
    	[DataMember]
        public Nullable<int> idFueFin { get; set; }
    	[DataMember]
        public Nullable<int> fechaPre { get; set; }
    	[DataMember]
        public Nullable<int> modalidad { get; set; }
    	[DataMember]
        public Nullable<int> organoEncargado { get; set; }
    	[DataMember]
        public string observaciones { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual Unidad Unidad { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        public virtual FuenteFinanciamiento FuenteFinanciamiento { get; set; }
        public virtual PlanAnualAdquisicionRequerimiento PlanAnualAdquisicionRequerimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PlanAnualAdquisicionDetalleMes> PlanAnualAdquisicionDetalleMes { get; set; }
    }
}
