//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PrecioBienServicioPorGruPrePres
    {
    	[DataMember]
        public string doc { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public Nullable<int> estado { get; set; }
    	[DataMember]
        public Nullable<int> anio { get; set; }
    	[DataMember]
        public Nullable<int> mes { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<int> dia { get; set; }
    	[DataMember]
        public Nullable<int> anioPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> mesPresupuesto { get; set; }
    	[DataMember]
        public string nomMes { get; set; }
    	[DataMember]
        public string prodServ { get; set; }
    	[DataMember]
        public string umedida { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public Nullable<decimal> subTotal { get; set; }
    	[DataMember]
        public Nullable<int> idProveedor { get; set; }
    	[DataMember]
        public string ruc { get; set; }
    	[DataMember]
        public string razonSocial { get; set; }
    	[DataMember]
        public Nullable<int> idUbigeo { get; set; }
    	[DataMember]
        public Nullable<int> idDireccion { get; set; }
    	[DataMember]
        public Nullable<int> idSubdireccion { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public Nullable<int> idProAnu { get; set; }
    	[DataMember]
        public Nullable<int> idSubpresupuesto { get; set; }
    	[DataMember]
        public string desGrupopresupuesto { get; set; }
    	[DataMember]
        public string desSubpresupuesto { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public string observacion { get; set; }
    	[DataMember]
        public string numCuentaV { get; set; }
    	[DataMember]
        public string desCuentaV { get; set; }
    	[DataMember]
        public string cuenta { get; set; }
    	[DataMember]
        public string subcuenta { get; set; }
    	[DataMember]
        public string divisionaria { get; set; }
    }
}
