//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PresupuestoRecepcionado
    {
    	[DataMember]
        public int idPreRec { get; set; }
    	[DataMember]
        public int idGruPre { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public int mes { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    	[DataMember]
        public string tipo { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public Nullable<int> estado { get; set; }
    	[DataMember]
        public Nullable<int> idPreRecOrigen { get; set; }
    
        public virtual GrupoPresupuesto GrupoPresupuesto { get; set; }
    }
}
