//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PresupuestoRemuneracionDet
    {
    	[DataMember]
        public int idPreRemDet { get; set; }
    	[DataMember]
        public int idPreRem { get; set; }
    	[DataMember]
        public int idProPreRem { get; set; }
    	[DataMember]
        public int mes { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual PresupuestoRemuneracion PresupuestoRemuneracion { get; set; }
        public virtual PropiedadPresupuestoRemuneracion PropiedadPresupuestoRemuneracion { get; set; }
    }
}
