//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PresupuestoRemuneracionExporta
    {
    	[DataMember]
        public int idPuePre { get; set; }
    	[DataMember]
        public string trabajador { get; set; }
    	[DataMember]
        public string cargo { get; set; }
    	[DataMember]
        public int grado { get; set; }
    	[DataMember]
        public decimal remuneracion { get; set; }
    	[DataMember]
        public decimal Bonfi { get; set; }
    	[DataMember]
        public decimal Alim { get; set; }
    	[DataMember]
        public decimal Movi { get; set; }
    	[DataMember]
        public decimal tIngreso { get; set; }
    	[DataMember]
        public Nullable<int> mes { get; set; }
    	[DataMember]
        public string nomMes { get; set; }
    	[DataMember]
        public Nullable<decimal> sueldo { get; set; }
    	[DataMember]
        public Nullable<decimal> salario { get; set; }
    	[DataMember]
        public Nullable<decimal> grati { get; set; }
    	[DataMember]
        public Nullable<decimal> vaca { get; set; }
    	[DataMember]
        public Nullable<decimal> escol { get; set; }
    	[DataMember]
        public Nullable<decimal> bonifProd { get; set; }
    	[DataMember]
        public Nullable<decimal> bonifExtr { get; set; }
    	[DataMember]
        public Nullable<decimal> vAlim { get; set; }
    	[DataMember]
        public Nullable<decimal> vMov { get; set; }
    	[DataMember]
        public Nullable<decimal> rcsss { get; set; }
    	[DataMember]
        public Nullable<decimal> segVida { get; set; }
    	[DataMember]
        public Nullable<decimal> cts { get; set; }
    	[DataMember]
        public Nullable<decimal> totalGasto { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string categoria { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public Nullable<int> ordenCat { get; set; }
    }
}
