//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ProductoDenominador = new HashSet<ProductoDenominador>();
            this.RequerimientoMensualDetalle = new HashSet<RequerimientoMensualDetalle>();
        }
    
    	[DataMember]
        public int idProducto { get; set; }
    	[DataMember]
        public int idModelo { get; set; }
    	[DataMember]
        public int idUnidad { get; set; }
    	[DataMember]
        public string Descripcion { get; set; }
    	[DataMember]
        public string Abreviado { get; set; }
    	[DataMember]
        public decimal Peso { get; set; }
    	[DataMember]
        public decimal stockMin { get; set; }
    	[DataMember]
        public decimal stockMax { get; set; }
    	[DataMember]
        public bool estado { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaCrea { get; set; }
    	[DataMember]
        public string usuMod { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMod { get; set; }
    	[DataMember]
        public string CodProductoAct { get; set; }
    
        public virtual Unidad Unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProductoDenominador> ProductoDenominador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoMensualDetalle> RequerimientoMensualDetalle { get; set; }
    }
}
