//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ProductoDenominador
    {
    	[DataMember]
        public int idProDeno { get; set; }
    	[DataMember]
        public int idProducto { get; set; }
    	[DataMember]
        public int idDenominador { get; set; }
    	[DataMember]
        public string codigo { get; set; }
    	[DataMember]
        public System.DateTime fechaDesde { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaHasta { get; set; }
    	[DataMember]
        public bool estado { get; set; }
    
        public virtual Denominador Denominador { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
