//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ProgramacionAnual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramacionAnual()
        {
            this.EvaluacionMensualProgramacion = new HashSet<EvaluacionMensualProgramacion>();
            this.ProgramacionAnualArea = new HashSet<ProgramacionAnualArea>();
            this.ProgramacionAnualEjeOperativo = new HashSet<ProgramacionAnualEjeOperativo>();
            this.ProgramacionAnualSede = new HashSet<ProgramacionAnualSede>();
            this.PuestoPresupuesto = new HashSet<PuestoPresupuesto>();
            this.ReajusteMensualProgramacion = new HashSet<ReajusteMensualProgramacion>();
            this.RequerimientoMensualBienServicio = new HashSet<RequerimientoMensualBienServicio>();
            this.Subpresupuesto = new HashSet<Subpresupuesto>();
        }
    
    	[DataMember]
        public int idProAnu { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public Nullable<int> idFueFin { get; set; }
    	[DataMember]
        public Nullable<int> nroTransferencia { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public System.DateTime fechaEmision { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaLiquidacion { get; set; }
    	[DataMember]
        public string tipo { get; set; }
    	[DataMember]
        public int idMoneda { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public Nullable<int> idPoaVersion { get; set; }
    	[DataMember]
        public Nullable<int> idModalidad { get; set; }
    	[DataMember]
        public Nullable<int> idTipoActividad { get; set; }
    	[DataMember]
        public Nullable<int> metaHa { get; set; }
    	[DataMember]
        public Nullable<decimal> costoxHa { get; set; }
    	[DataMember]
        public string denominacion { get; set; }
    	[DataMember]
        public string observacion { get; set; }
    	[DataMember]
        public Nullable<int> idEstPreRem { get; set; }
    	[DataMember]
        public Nullable<int> mesDesdeRem { get; set; }
    	[DataMember]
        public Nullable<int> mesHastaRem { get; set; }
    	[DataMember]
        public bool esSaldo { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<EvaluacionMensualProgramacion> EvaluacionMensualProgramacion { get; set; }
        public virtual FuenteFinanciamiento FuenteFinanciamiento { get; set; }
        public virtual GrupoPresupuesto GrupoPresupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualArea> ProgramacionAnualArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualEjeOperativo> ProgramacionAnualEjeOperativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualSede> ProgramacionAnualSede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PuestoPresupuesto> PuestoPresupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualProgramacion> ReajusteMensualProgramacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoMensualBienServicio> RequerimientoMensualBienServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<Subpresupuesto> Subpresupuesto { get; set; }
        public virtual PoaVersion PoaVersion { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
    }
}
