//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ProgramacionAnualArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramacionAnualArea()
        {
            this.ProgramacionAnualAreaMes = new HashSet<ProgramacionAnualAreaMes>();
            this.EvaluacionMensualProgramacionArea = new HashSet<EvaluacionMensualProgramacionArea>();
            this.ReajusteMensualProgramacionArea = new HashSet<ReajusteMensualProgramacionArea>();
            this.ProgramacionAnualDetalle = new HashSet<ProgramacionAnualDetalle>();
        }
    
    	[DataMember]
        public int idProAnuArea { get; set; }
    	[DataMember]
        public int idProAnu { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public int idArea { get; set; }
    	[DataMember]
        public Nullable<int> idUnidad { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualAreaMes> ProgramacionAnualAreaMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<EvaluacionMensualProgramacionArea> EvaluacionMensualProgramacionArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualProgramacionArea> ReajusteMensualProgramacionArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualDetalle> ProgramacionAnualDetalle { get; set; }
        public virtual ProgramacionAnual ProgramacionAnual { get; set; }
    }
}
