//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ProgramacionAnualDetallePorMesPres
    {
    	[DataMember]
        public int idProAnu { get; set; }
    	[DataMember]
        public int idProAnuArea { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public int idArea { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public int idProAnuAreaMes { get; set; }
    	[DataMember]
        public int mes { get; set; }
    	[DataMember]
        public int idProAnuDet { get; set; }
    	[DataMember]
        public string desDetalle { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public int idUnidad { get; set; }
    	[DataMember]
        public int idProAnuDetMes { get; set; }
    	[DataMember]
        public Nullable<int> idSubpresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> dias { get; set; }
    	[DataMember]
        public decimal cantidad { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    }
}
