//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ProgramacionAnualPlanAdqDetalleMes
    {
    	[DataMember]
        public int idProAnuPlanDetMes { get; set; }
    	[DataMember]
        public int idProAnuDetMes { get; set; }
    	[DataMember]
        public int idPaaDetMes { get; set; }
    
        public virtual PlanAnualAdquisicionDetalleMes PlanAnualAdquisicionDetalleMes { get; set; }
        public virtual ProgramacionAnualDetalleMes ProgramacionAnualDetalleMes { get; set; }
    }
}
