//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PropiedadPresupuestoRemuneracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropiedadPresupuestoRemuneracion()
        {
            this.PresupuestoRemuneracionDet = new HashSet<PresupuestoRemuneracionDet>();
            this.ReajustePresupuestoRemuneracionDet = new HashSet<ReajustePresupuestoRemuneracionDet>();
        }
    
    	[DataMember]
        public int idProPreRem { get; set; }
    	[DataMember]
        public int idEstPreRem { get; set; }
    	[DataMember]
        public int idConPreRem { get; set; }
    	[DataMember]
        public string tipoValor { get; set; }
    	[DataMember]
        public string valor { get; set; }
    	[DataMember]
        public bool visualiza { get; set; }
    	[DataMember]
        public int orden { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual EstructuraPresupuestoRemuneracion EstructuraPresupuestoRemuneracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PresupuestoRemuneracionDet> PresupuestoRemuneracionDet { get; set; }
        public virtual ConceptoPresupuestoRemuneracion ConceptoPresupuestoRemuneracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajustePresupuestoRemuneracionDet> ReajustePresupuestoRemuneracionDet { get; set; }
    }
}
