//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class PuestoRequerimientoAnualPres
    {
    	[DataMember]
        public Nullable<long> item { get; set; }
    	[DataMember]
        public Nullable<int> idPueReq { get; set; }
    	[DataMember]
        public Nullable<int> idTrabajador { get; set; }
    	[DataMember]
        public string nroDocIdentidad { get; set; }
    	[DataMember]
        public string persona { get; set; }
    	[DataMember]
        public Nullable<decimal> remuneracion { get; set; }
    	[DataMember]
        public Nullable<int> grado { get; set; }
    	[DataMember]
        public string cargo { get; set; }
    	[DataMember]
        public string esRemDiaria { get; set; }
    	[DataMember]
        public Nullable<int> cantVacante { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public Nullable<bool> esSeleccionado { get; set; }
    }
}
