//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReajusteMensualArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReajusteMensualArea()
        {
            this.ReajusteMensualAreaMes = new HashSet<ReajusteMensualAreaMes>();
            this.ReajusteMensualProgramacionArea = new HashSet<ReajusteMensualProgramacionArea>();
            this.RequerimientoReajusteMensual = new HashSet<RequerimientoReajusteMensual>();
            this.ReajusteMensualDetalle = new HashSet<ReajusteMensualDetalle>();
        }
    
    	[DataMember]
        public int idReaMenArea { get; set; }
    	[DataMember]
        public Nullable<int> idReaMenPro { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public int idArea { get; set; }
    	[DataMember]
        public Nullable<int> idUnidad { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualAreaMes> ReajusteMensualAreaMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualProgramacionArea> ReajusteMensualProgramacionArea { get; set; }
        public virtual ReajusteMensualProgramacion ReajusteMensualProgramacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoReajusteMensual> RequerimientoReajusteMensual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualDetalle> ReajusteMensualDetalle { get; set; }
    }
}
