//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReajusteMensualAreaPres
    {
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> idReaMenArea { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string numCuentaNivel2 { get; set; }
    	[DataMember]
        public string descripcionNivel2 { get; set; }
    	[DataMember]
        public string numCuentaNivel1 { get; set; }
    	[DataMember]
        public string descripcionNivel1 { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public Nullable<decimal> enero { get; set; }
    	[DataMember]
        public Nullable<decimal> febrero { get; set; }
    	[DataMember]
        public Nullable<decimal> marzo { get; set; }
    	[DataMember]
        public Nullable<decimal> abril { get; set; }
    	[DataMember]
        public Nullable<decimal> mayo { get; set; }
    	[DataMember]
        public Nullable<decimal> junio { get; set; }
    	[DataMember]
        public Nullable<decimal> julio { get; set; }
    	[DataMember]
        public Nullable<decimal> agosto { get; set; }
    	[DataMember]
        public Nullable<decimal> setiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> octubre { get; set; }
    	[DataMember]
        public Nullable<decimal> noviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> diciembre { get; set; }
    	[DataMember]
        public Nullable<decimal> total { get; set; }
    }
}
