//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReajusteMensualPresupuestoPres
    {
    	[DataMember]
        public int idReaMenPro { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string presupuestoAnual { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public Nullable<int> anio { get; set; }
    	[DataMember]
        public string mesReajuste { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public string tipo { get; set; }
    	[DataMember]
        public Nullable<decimal> total { get; set; }
    }
}
