//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteRequerimientoMensualSeguimientoPres
    {
    	[DataMember]
        public Nullable<int> idDet { get; set; }
    	[DataMember]
        public Nullable<int> idMoneda { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public Nullable<decimal> importeOrigen { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public string numDivisionaria { get; set; }
    	[DataMember]
        public string numClase { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string esPresupuestado { get; set; }
    	[DataMember]
        public string proceso { get; set; }
    	[DataMember]
        public string desCuentaClase { get; set; }
    	[DataMember]
        public string desCuentaDivisionaria { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    }
}
