//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReportePresupuestoAprobadoComprometidoEjecutadoPres
    {
    	[DataMember]
        public Nullable<long> item { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public string nomGrupoPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public string nomPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idSubpresupuesto { get; set; }
    	[DataMember]
        public string nomSubPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> clase { get; set; }
    	[DataMember]
        public string desClase { get; set; }
    	[DataMember]
        public Nullable<int> divisionaria { get; set; }
    	[DataMember]
        public string desDivisionaria { get; set; }
    	[DataMember]
        public Nullable<int> numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public Nullable<decimal> monPre { get; set; }
    	[DataMember]
        public Nullable<decimal> monCom { get; set; }
    	[DataMember]
        public Nullable<decimal> monEjeAct { get; set; }
    	[DataMember]
        public Nullable<decimal> saldo { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    }
}
