//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteRequerimientoRRHHDireccionImportePres
    {
    	[DataMember]
        public Nullable<int> idPueReq { get; set; }
    	[DataMember]
        public Nullable<int> idReqRecHum { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSede { get; set; }
    	[DataMember]
        public Nullable<int> idCargo { get; set; }
    	[DataMember]
        public string desCargo { get; set; }
    	[DataMember]
        public Nullable<int> grado { get; set; }
    	[DataMember]
        public Nullable<int> nivel { get; set; }
    	[DataMember]
        public string desMoneda { get; set; }
    	[DataMember]
        public Nullable<decimal> remuneracionFinal { get; set; }
    	[DataMember]
        public Nullable<bool> esRemDiaria { get; set; }
    	[DataMember]
        public Nullable<int> cantidad { get; set; }
    	[DataMember]
        public Nullable<int> cantEnero { get; set; }
    	[DataMember]
        public Nullable<decimal> remEnero { get; set; }
    	[DataMember]
        public Nullable<int> cantFebrero { get; set; }
    	[DataMember]
        public Nullable<decimal> remFebrero { get; set; }
    	[DataMember]
        public Nullable<int> cantMarzo { get; set; }
    	[DataMember]
        public Nullable<decimal> remMarzo { get; set; }
    	[DataMember]
        public Nullable<int> cantAbril { get; set; }
    	[DataMember]
        public Nullable<decimal> remAbril { get; set; }
    	[DataMember]
        public Nullable<int> cantMayo { get; set; }
    	[DataMember]
        public Nullable<decimal> remMayo { get; set; }
    	[DataMember]
        public Nullable<int> cantJunio { get; set; }
    	[DataMember]
        public Nullable<decimal> remJunio { get; set; }
    	[DataMember]
        public Nullable<int> cantJulio { get; set; }
    	[DataMember]
        public Nullable<decimal> remJulio { get; set; }
    	[DataMember]
        public Nullable<int> cantAgosto { get; set; }
    	[DataMember]
        public Nullable<decimal> remAgosto { get; set; }
    	[DataMember]
        public Nullable<int> cantSetiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> remSetiembre { get; set; }
    	[DataMember]
        public Nullable<int> cantOctubre { get; set; }
    	[DataMember]
        public Nullable<decimal> remOctubre { get; set; }
    	[DataMember]
        public Nullable<int> cantNoviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> remNoviembre { get; set; }
    	[DataMember]
        public Nullable<int> cantDiciembre { get; set; }
    	[DataMember]
        public Nullable<decimal> remDiciembre { get; set; }
    }
}
