//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReportePresupuestoFasesPres
    {
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public Nullable<decimal> pia { get; set; }
    	[DataMember]
        public Nullable<decimal> pim { get; set; }
    	[DataMember]
        public Nullable<decimal> certificado { get; set; }
    	[DataMember]
        public Nullable<decimal> comprometido { get; set; }
    	[DataMember]
        public Nullable<decimal> provisionado { get; set; }
    	[DataMember]
        public Nullable<decimal> girado { get; set; }
    	[DataMember]
        public Nullable<int> nivel { get; set; }
    	[DataMember]
        public Nullable<int> dependencia { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string desMoneda { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public Nullable<int> orden { get; set; }
    }
}
