//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReportePresupuestoEjecutadoPres
    {
    	[DataMember]
        public Nullable<int> anioEmision { get; set; }
    	[DataMember]
        public Nullable<int> mesEmision { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public Nullable<int> dependencia { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public string desGruPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idSubpresupuesto { get; set; }
    	[DataMember]
        public string desSubpresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> anioPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> mesPresupuesto { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public string tipoOperacion { get; set; }
    	[DataMember]
        public string tipoEgreso { get; set; }
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> posicion { get; set; }
    	[DataMember]
        public string desGenerica { get; set; }
    	[DataMember]
        public string desMesPresupuesto { get; set; }
    	[DataMember]
        public string clase { get; set; }
    	[DataMember]
        public string desClase { get; set; }
    	[DataMember]
        public string divisionaria { get; set; }
    	[DataMember]
        public string desDivisionaria { get; set; }
    	[DataMember]
        public string desMesEmision { get; set; }
    }
}
