//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteRequerimientoMensualSeguimientoForebisePres
    {
    	[DataMember]
        public Nullable<int> id { get; set; }
    	[DataMember]
        public string codigo { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public string desSubpresupuesto { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string desSubDireccion { get; set; }
    	[DataMember]
        public Nullable<int> estado { get; set; }
    	[DataMember]
        public string desEstado { get; set; }
    	[DataMember]
        public string nroCertificacion { get; set; }
    	[DataMember]
        public string nroOrden { get; set; }
    	[DataMember]
        public Nullable<decimal> importeCertificacion { get; set; }
    	[DataMember]
        public Nullable<decimal> importeOrden { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public string descripcionDetalle { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    }
}
