//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteRequerimientoRRHHPres
    {
    	[DataMember]
        public int idPueReq { get; set; }
    	[DataMember]
        public int idPersona { get; set; }
    	[DataMember]
        public string dni { get; set; }
    	[DataMember]
        public string trabajador { get; set; }
    	[DataMember]
        public string codCargo { get; set; }
    	[DataMember]
        public string desCargo { get; set; }
    	[DataMember]
        public int grado { get; set; }
    	[DataMember]
        public decimal remuneracion { get; set; }
    	[DataMember]
        public string codCargoPro { get; set; }
    	[DataMember]
        public string desCargoPro { get; set; }
    	[DataMember]
        public Nullable<int> gradoPropuesto { get; set; }
    	[DataMember]
        public Nullable<decimal> remPropuesta { get; set; }
    	[DataMember]
        public string desSede { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desFueFin { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string simboloMoneda { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public int idCatLab { get; set; }
    	[DataMember]
        public string catLaboral { get; set; }
    	[DataMember]
        public int idConLab { get; set; }
    	[DataMember]
        public string conLaboral { get; set; }
    	[DataMember]
        public Nullable<int> ordGruCatLab { get; set; }
    	[DataMember]
        public string grupoCatLab { get; set; }
    	[DataMember]
        public string codSede { get; set; }
    	[DataMember]
        public int ordenDireccion { get; set; }
    	[DataMember]
        public string codArea { get; set; }
    	[DataMember]
        public Nullable<int> cantidad { get; set; }
    }
}
