//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReportePresupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportePresupuesto()
        {
            this.ReportePresupuestoDetalle = new HashSet<ReportePresupuestoDetalle>();
        }
    
    	[DataMember]
        public int idRepPre { get; set; }
    	[DataMember]
        public int idTipRep { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    
        public virtual TipoReporte TipoReporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReportePresupuestoDetalle> ReportePresupuestoDetalle { get; set; }
    }
}
