//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteOrdenCompraServicioComprometidasPres
    {
    	[DataMember]
        public int idOrden { get; set; }
    	[DataMember]
        public Nullable<int> idProveedor { get; set; }
    	[DataMember]
        public string ruc { get; set; }
    	[DataMember]
        public string nombre { get; set; }
    	[DataMember]
        public string tipo { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public Nullable<int> idSubpresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public string desSubpresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public string desGruPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> estado1 { get; set; }
    	[DataMember]
        public Nullable<int> estado2 { get; set; }
    	[DataMember]
        public string desEstado { get; set; }
    }
}
