//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteRequerimientoMensualSeguimientoDetalleForebisePres
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public Nullable<int> idDet { get; set; }
    	[DataMember]
        public Nullable<int> idCab { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaMov { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public string glosa { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public Nullable<int> dependencia { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    }
}
