//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteCertificacionPresupuestalPres
    {
    	[DataMember]
        public Nullable<int> idCerReq { get; set; }
    	[DataMember]
        public Nullable<int> tipoReq { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string sigla { get; set; }
    	[DataMember]
        public string actividadProyecto { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<int> idCerDet { get; set; }
    	[DataMember]
        public Nullable<int> idProAnuReaMen { get; set; }
    	[DataMember]
        public Nullable<int> tipoDet { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public Nullable<decimal> saldoSoles { get; set; }
    	[DataMember]
        public Nullable<decimal> saldoDolares { get; set; }
    	[DataMember]
        public Nullable<int> idForReqDet { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public string codigo { get; set; }
    	[DataMember]
        public string numero { get; set; }
    	[DataMember]
        public string desGruPresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public string desSubPresupuesto { get; set; }
    	[DataMember]
        public string periodo { get; set; }
    	[DataMember]
        public Nullable<decimal> tipocambio { get; set; }
    	[DataMember]
        public string fuenteFinanciamiento { get; set; }
    	[DataMember]
        public string observacion { get; set; }
    	[DataMember]
        public Nullable<bool> esAmpliacion { get; set; }
    	[DataMember]
        public string detalle { get; set; }
    }
}
