//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteSubpresupuestoDetalleExportaPres
    {
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> idProAnuDet { get; set; }
    	[DataMember]
        public Nullable<int> idProAnuArea { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string Abreviado { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public decimal cantidad { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public int dias { get; set; }
    }
}
