//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReportePresupuestoDetalle
    {
    	[DataMember]
        public int idRepPreDet { get; set; }
    	[DataMember]
        public int idRepPre { get; set; }
    	[DataMember]
        public int idPresupuesto { get; set; }
    	[DataMember]
        public int nivelPresupuesto { get; set; }
    
        public virtual ReportePresupuesto ReportePresupuesto { get; set; }
    }
}
