//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteCertificacionOrdenProvisionPres
    {
    	[DataMember]
        public int idCerMas { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public string desSubpresupuesto { get; set; }
    	[DataMember]
        public int tipoReq { get; set; }
    	[DataMember]
        public string descripcionTipoReq { get; set; }
    	[DataMember]
        public int idForebise { get; set; }
    	[DataMember]
        public string numeroReq { get; set; }
    	[DataMember]
        public string estadoReq { get; set; }
    	[DataMember]
        public string numCertificacion { get; set; }
    	[DataMember]
        public Nullable<decimal> totalCerticado { get; set; }
    	[DataMember]
        public string numOrden { get; set; }
    	[DataMember]
        public Nullable<decimal> importeOrden { get; set; }
    	[DataMember]
        public Nullable<decimal> importeProvicion { get; set; }
    	[DataMember]
        public Nullable<decimal> importePendiente { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    }
}
