//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReportePresupuestoEjecutadoFondosPres
    {
    	[DataMember]
        public Nullable<long> item { get; set; }
    	[DataMember]
        public string tipoOpe { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public string nomGrupoPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public string nomPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idSubpresupuesto { get; set; }
    	[DataMember]
        public string nomSubPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> clase { get; set; }
    	[DataMember]
        public string desClase { get; set; }
    	[DataMember]
        public Nullable<int> divisionaria { get; set; }
    	[DataMember]
        public string desDivisionaria { get; set; }
    	[DataMember]
        public Nullable<int> anioCuenta { get; set; }
    	[DataMember]
        public Nullable<decimal> monEjeAct { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public Nullable<int> numMes { get; set; }
    	[DataMember]
        public Nullable<int> numAnio { get; set; }
    	[DataMember]
        public string mes { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public Nullable<int> numCuenta { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public Nullable<int> anioEmi { get; set; }
    	[DataMember]
        public string mesEmi { get; set; }
    	[DataMember]
        public string tipoegreso { get; set; }
    	[DataMember]
        public Nullable<int> idPresCuentaServRem { get; set; }
    	[DataMember]
        public Nullable<int> idtipoBienRem { get; set; }
    	[DataMember]
        public Nullable<int> codCuenta { get; set; }
    	[DataMember]
        public Nullable<int> idTipoBienRem1 { get; set; }
    	[DataMember]
        public string NomTipoBienRem { get; set; }
    	[DataMember]
        public string nomPres { get; set; }
    	[DataMember]
        public string nomTipoFondo { get; set; }
    	[DataMember]
        public Nullable<int> anioEmi1 { get; set; }
    	[DataMember]
        public string mesEmision { get; set; }
    }
}
