//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ReporteGastoRecurrenteDetalleDireccionPres
    {
    	[DataMember]
        public Nullable<int> idgasrecDet { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string grupoPresupuesto { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string numCuentaNivel1 { get; set; }
    	[DataMember]
        public string descripcionNivel1 { get; set; }
    	[DataMember]
        public string numCuentaNivel2 { get; set; }
    	[DataMember]
        public string descripcionNivel2 { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcionCuenta { get; set; }
    	[DataMember]
        public string endtidad { get; set; }
    	[DataMember]
        public string ruc { get; set; }
    	[DataMember]
        public Nullable<int> anio { get; set; }
    	[DataMember]
        public string desDetalle { get; set; }
    	[DataMember]
        public string Abreviado { get; set; }
    	[DataMember]
        public decimal cant { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public Nullable<decimal> subTotal { get; set; }
    	[DataMember]
        public string abreviatura { get; set; }
    	[DataMember]
        public decimal tipoCambio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public Nullable<decimal> cantEnero { get; set; }
    	[DataMember]
        public Nullable<decimal> cantFebrero { get; set; }
    	[DataMember]
        public Nullable<decimal> cantMarzo { get; set; }
    	[DataMember]
        public Nullable<decimal> cantAbril { get; set; }
    	[DataMember]
        public Nullable<decimal> cantMayo { get; set; }
    	[DataMember]
        public Nullable<decimal> cantJunio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantJulio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantAgosto { get; set; }
    	[DataMember]
        public Nullable<decimal> cantSetiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantOctubre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantNoviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantDiciembre { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    }
}
