//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoMensualDetallePres
    {
    	[DataMember]
        public Nullable<long> item { get; set; }
    	[DataMember]
        public int idReqMenDet { get; set; }
    	[DataMember]
        public int idReqMenBieSer { get; set; }
    	[DataMember]
        public string desProSer { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public int idUnidad { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public decimal cantidad { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public decimal cantPresupuestada { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string tipoRequerimiento { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public string desMes { get; set; }
    	[DataMember]
        public System.DateTime fechaEmision { get; set; }
    	[DataMember]
        public string desMoneda { get; set; }
    	[DataMember]
        public string desEstado { get; set; }
    }
}
