//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoBienServicioPendientePorCuentaPres
    {
    	[DataMember]
        public Nullable<int> idReqBieSer { get; set; }
    	[DataMember]
        public Nullable<int> idReqBieSerDet { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string desReqDetalle { get; set; }
    	[DataMember]
        public Nullable<int> idCueCon { get; set; }
    	[DataMember]
        public Nullable<int> idUnidad { get; set; }
    	[DataMember]
        public Nullable<int> idProducto { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public Nullable<int> idArea { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public Nullable<decimal> precioOrigen { get; set; }
    	[DataMember]
        public decimal cant { get; set; }
    	[DataMember]
        public Nullable<decimal> subtotal { get; set; }
    }
}
