//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoRecursoHumanoDetallePres
    {
    	[DataMember]
        public int idPueReq { get; set; }
    	[DataMember]
        public int idReqRecHum { get; set; }
    	[DataMember]
        public Nullable<int> idTrabajador { get; set; }
    	[DataMember]
        public string dni { get; set; }
    	[DataMember]
        public string trabajador { get; set; }
    	[DataMember]
        public decimal remuneracion { get; set; }
    	[DataMember]
        public int grado { get; set; }
    	[DataMember]
        public string cargo { get; set; }
    	[DataMember]
        public string esRemDiaria { get; set; }
    	[DataMember]
        public int cantVacante { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public string desFueFin { get; set; }
    }
}
