//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoBienServicioDetallePresExporta
    {
    	[DataMember]
        public Nullable<long> posicion { get; set; }
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> idReqBieSerDet { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string codDireccion { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public int orden { get; set; }
    	[DataMember]
        public Nullable<decimal> cantEnero { get; set; }
    	[DataMember]
        public Nullable<decimal> cantFebrero { get; set; }
    	[DataMember]
        public Nullable<decimal> cantMarzo { get; set; }
    	[DataMember]
        public Nullable<decimal> cantAbril { get; set; }
    	[DataMember]
        public Nullable<decimal> cantMayo { get; set; }
    	[DataMember]
        public Nullable<decimal> cantJunio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantJulio { get; set; }
    	[DataMember]
        public Nullable<decimal> cantAgosto { get; set; }
    	[DataMember]
        public Nullable<decimal> cantSetiembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantOctubre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantNoviembre { get; set; }
    	[DataMember]
        public Nullable<decimal> cantDiciembre { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public Nullable<decimal> subtotal { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public int nivel { get; set; }
    }
}
