//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoRecursoHumanoPres
    {
    	[DataMember]
        public int idReqRecHum { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public System.DateTime fechaEmision { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
    	[DataMember]
        public string moneda { get; set; }
    	[DataMember]
        public int anio { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public Nullable<int> cantTotalPuesto { get; set; }
    	[DataMember]
        public Nullable<int> cantTotalEmpleado { get; set; }
    	[DataMember]
        public Nullable<int> cantTotalObrero { get; set; }
    }
}
