//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoMensualDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequerimientoMensualDetalle()
        {
            this.ReajusteMensualDetalle = new HashSet<ReajusteMensualDetalle>();
        }
    
    	[DataMember]
        public int idReqMenDet { get; set; }
    	[DataMember]
        public int idReqMenBieSer { get; set; }
    	[DataMember]
        public Nullable<int> idParPre { get; set; }
    	[DataMember]
        public Nullable<int> idProducto { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public int idUnidad { get; set; }
    	[DataMember]
        public decimal precio { get; set; }
    	[DataMember]
        public decimal cantidad { get; set; }
    	[DataMember]
        public decimal cantPresupuestada { get; set; }
    	[DataMember]
        public decimal importe { get; set; }
    	[DataMember]
        public Nullable<int> idTipIng { get; set; }
    	[DataMember]
        public string codPat { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public byte[] docReferencia { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Unidad Unidad { get; set; }
        public virtual PartidaPresupuestal PartidaPresupuestal { get; set; }
        public virtual RequerimientoMensualBienServicio RequerimientoMensualBienServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualDetalle> ReajusteMensualDetalle { get; set; }
    }
}
