//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class RequerimientoReajusteMensual
    {
    	[DataMember]
        public int idReqReaMen { get; set; }
    	[DataMember]
        public int idReqMenBieSer { get; set; }
    	[DataMember]
        public int idReaMenArea { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    
        public virtual ReajusteMensualArea ReajusteMensualArea { get; set; }
        public virtual RequerimientoMensualBienServicio RequerimientoMensualBienServicio { get; set; }
    }
}
