//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ResumenEvaFinanCorahSaal
    {
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public decimal recepcionado { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public decimal saldo { get; set; }
    	[DataMember]
        public decimal recepSoles { get; set; }
    	[DataMember]
        public decimal impSoles { get; set; }
    	[DataMember]
        public decimal saldoSoles { get; set; }
    	[DataMember]
        public string tipoReporte { get; set; }
    }
}
