//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class SaldosEvaReaPorDir
    {
    	[DataMember]
        public Nullable<long> item { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public Nullable<decimal> EVADevida { get; set; }
    	[DataMember]
        public Nullable<decimal> EVASaal { get; set; }
    	[DataMember]
        public Nullable<decimal> EVAOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> EVA { get; set; }
    	[DataMember]
        public Nullable<decimal> READevida { get; set; }
    	[DataMember]
        public Nullable<decimal> REASaal { get; set; }
    	[DataMember]
        public Nullable<decimal> REAOtros { get; set; }
    	[DataMember]
        public Nullable<decimal> REA { get; set; }
    	[DataMember]
        public Nullable<decimal> Devida { get; set; }
    	[DataMember]
        public Nullable<decimal> Saal { get; set; }
    	[DataMember]
        public Nullable<decimal> Otros { get; set; }
    	[DataMember]
        public Nullable<decimal> total { get; set; }
    	[DataMember]
        public string titulo { get; set; }
    	[DataMember]
        public string tituloMon { get; set; }
    	[DataMember]
        public string tituloTotal { get; set; }
    	[DataMember]
        public string tituloEVA { get; set; }
    	[DataMember]
        public string tituloREA { get; set; }
    	[DataMember]
        public int grupo { get; set; }
    	[DataMember]
        public string tituloOtros { get; set; }
    	[DataMember]
        public string tituloTotalMonto { get; set; }
    	[DataMember]
        public string tituloGrupo { get; set; }
    }
}
