//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class SedeLaboral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SedeLaboral()
        {
            this.ProgramacionAnualSede = new HashSet<ProgramacionAnualSede>();
            this.PuestoReajustePresupuesto = new HashSet<PuestoReajustePresupuesto>();
            this.PuestoPresupuesto = new HashSet<PuestoPresupuesto>();
        }
    
    	[DataMember]
        public int idSede { get; set; }
    	[DataMember]
        public int idUbigeo { get; set; }
    	[DataMember]
        public string codSede { get; set; }
    	[DataMember]
        public string desSede { get; set; }
    
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualSede> ProgramacionAnualSede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PuestoReajustePresupuesto> PuestoReajustePresupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PuestoPresupuesto> PuestoPresupuesto { get; set; }
    }
}
