//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class SubPresupuestoImporteCertificacion_Pres
    {
    	[DataMember]
        public int idSubpresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> anio { get; set; }
    	[DataMember]
        public Nullable<int> mes { get; set; }
    	[DataMember]
        public Nullable<bool> esObra { get; set; }
    	[DataMember]
        public Nullable<bool> esEncargo { get; set; }
    	[DataMember]
        public Nullable<bool> esActividadCampo { get; set; }
    	[DataMember]
        public Nullable<bool> esErradicacion { get; set; }
    	[DataMember]
        public Nullable<bool> esLiquidado { get; set; }
    	[DataMember]
        public Nullable<decimal> tipoCambio { get; set; }
    	[DataMember]
        public int estado { get; set; }
    	[DataMember]
        public string desSubPresupuesto { get; set; }
    	[DataMember]
        public int idPresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public string desGrupoPresupuesto { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string cuentaBancaria { get; set; }
    	[DataMember]
        public string proyecto { get; set; }
    	[DataMember]
        public decimal importeObra { get; set; }
    	[DataMember]
        public Nullable<decimal> certificacionSoles { get; set; }
    	[DataMember]
        public Nullable<decimal> certificacionDolares { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public string nombreEstado { get; set; }
    }
}
