//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class SubPresupuestoDetallePres
    {
    	[DataMember]
        public int idProAnuReaMen { get; set; }
    	[DataMember]
        public int tipoDet { get; set; }
    	[DataMember]
        public int idCueCon { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string desCuenta { get; set; }
    	[DataMember]
        public decimal importePreSoles { get; set; }
    	[DataMember]
        public decimal importeEjeSoles { get; set; }
    	[DataMember]
        public decimal saldoSoles { get; set; }
    	[DataMember]
        public decimal importePreDolares { get; set; }
    	[DataMember]
        public decimal importeEjeDolares { get; set; }
    	[DataMember]
        public decimal saldoDolares { get; set; }
    }
}
