//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Subpresupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subpresupuesto()
        {
            this.ReajusteMensualDetalleMes = new HashSet<ReajusteMensualDetalleMes>();
            this.ProgramacionAnualDetalleMes = new HashSet<ProgramacionAnualDetalleMes>();
            this.CertificacionRequerimientoSubprespuesto = new HashSet<CertificacionRequerimientoSubprespuesto>();
        }
    
    	[DataMember]
        public int idSubpresupuesto { get; set; }
    	[DataMember]
        public int idProAnu { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string abreviatura { get; set; }
    	[DataMember]
        public string nroProyecto { get; set; }
    	[DataMember]
        public Nullable<bool> esObra { get; set; }
    	[DataMember]
        public Nullable<bool> esEncargo { get; set; }
    	[DataMember]
        public Nullable<bool> esActividadCampo { get; set; }
    	[DataMember]
        public Nullable<bool> esErradicacion { get; set; }
    	[DataMember]
        public Nullable<bool> esLiquidado { get; set; }
    	[DataMember]
        public Nullable<int> anio { get; set; }
    	[DataMember]
        public Nullable<int> mes { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public int estado { get; set; }
    	[DataMember]
        public Nullable<int> LIQSUBPPTO { get; set; }
    	[DataMember]
        public Nullable<decimal> DCTIPCAM { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ReajusteMensualDetalleMes> ReajusteMensualDetalleMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualDetalleMes> ProgramacionAnualDetalleMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<CertificacionRequerimientoSubprespuesto> CertificacionRequerimientoSubprespuesto { get; set; }
        public virtual ProgramacionAnual ProgramacionAnual { get; set; }
    }
}
