//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class SubPresupuestoAreaPres
    {
    	[DataMember]
        public Nullable<int> item { get; set; }
    	[DataMember]
        public Nullable<int> idProAnuArea { get; set; }
    	[DataMember]
        public string numCuenta { get; set; }
    	[DataMember]
        public string descripcion { get; set; }
    	[DataMember]
        public string desArea { get; set; }
    	[DataMember]
        public string desSubdireccion { get; set; }
    	[DataMember]
        public string desDireccion { get; set; }
    	[DataMember]
        public string numCuentaNivel2 { get; set; }
    	[DataMember]
        public string descripcionNivel2 { get; set; }
    	[DataMember]
        public string numCuentaNivel1 { get; set; }
    	[DataMember]
        public string descripcionNivel1 { get; set; }
    	[DataMember]
        public string grupo { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public int posicion { get; set; }
    	[DataMember]
        public int posGru { get; set; }
    }
}
