//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class SubPresupuestoPres
    {
    	[DataMember]
        public int idSubPresupuesto { get; set; }
    	[DataMember]
        public int idPresupuesto { get; set; }
    	[DataMember]
        public Nullable<bool> esObra { get; set; }
    	[DataMember]
        public Nullable<int> mes { get; set; }
    	[DataMember]
        public string proyecto { get; set; }
    	[DataMember]
        public int estado { get; set; }
    	[DataMember]
        public string nombreEstado { get; set; }
    	[DataMember]
        public string desSubPresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public string desGrupoPresupuesto { get; set; }
    	[DataMember]
        public string usuCrea { get; set; }
    	[DataMember]
        public System.DateTime fechaCrea { get; set; }
    	[DataMember]
        public string usuEdita { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEdita { get; set; }
    	[DataMember]
        public decimal tipoCambio { get; set; }
    }
}
