//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class TipoReporteGrupoPresupuesto
    {
    	[DataMember]
        public int idTipRepGruPre { get; set; }
    	[DataMember]
        public int idTipRep { get; set; }
    	[DataMember]
        public int idGruPre { get; set; }
    
        public virtual TipoReporte TipoReporte { get; set; }
        public virtual GrupoPresupuesto GrupoPresupuesto { get; set; }
    }
}
