//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Ubigeo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ubigeo()
        {
            this.Ubigeo1 = new HashSet<Ubigeo>();
            this.PlanAnualAdquisicionDetalle = new HashSet<PlanAnualAdquisicionDetalle>();
            this.SedeLaboral = new HashSet<SedeLaboral>();
        }
    
    	[DataMember]
        public int idUbigeo { get; set; }
    	[DataMember]
        public string codSunat { get; set; }
    	[DataMember]
        public string desUbigeo { get; set; }
    	[DataMember]
        public int dependencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<Ubigeo> Ubigeo1 { get; set; }
        public virtual Ubigeo Ubigeo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PlanAnualAdquisicionDetalle> PlanAnualAdquisicionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<SedeLaboral> SedeLaboral { get; set; }
    }
}
