//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Unidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unidad()
        {
            this.Producto = new HashSet<Producto>();
            this.PlanAnualAdquisicionDetalle = new HashSet<PlanAnualAdquisicionDetalle>();
            this.PartidaPresupuestal = new HashSet<PartidaPresupuestal>();
            this.RequerimientoBienServicioDetalle = new HashSet<RequerimientoBienServicioDetalle>();
            this.RequerimientoMensualDetalle = new HashSet<RequerimientoMensualDetalle>();
            this.ProgramacionAnualDetalle = new HashSet<ProgramacionAnualDetalle>();
        }
    
    	[DataMember]
        public int idUnidad { get; set; }
    	[DataMember]
        public string nomUnidad { get; set; }
    	[DataMember]
        public string Abreviado { get; set; }
    	[DataMember]
        public bool esUnidadMinima { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<Producto> Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PlanAnualAdquisicionDetalle> PlanAnualAdquisicionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<PartidaPresupuestal> PartidaPresupuestal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoBienServicioDetalle> RequerimientoBienServicioDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<RequerimientoMensualDetalle> RequerimientoMensualDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	//[DataMember]
        public virtual ICollection<ProgramacionAnualDetalle> ProgramacionAnualDetalle { get; set; }
    }
}
