//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class UsuarioCorreoPres
    {
    	[DataMember]
        public int idTrabajador { get; set; }
    	[DataMember]
        public string nombresCompletos { get; set; }
    	[DataMember]
        public string dni { get; set; }
    	[DataMember]
        public string nomUsuario { get; set; }
    	[DataMember]
        public string email { get; set; }
    }
}
