//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class vCotizacionCompra
    {
    	[DataMember]
        public int idCotizacion { get; set; }
    	[DataMember]
        public string numCotizacion { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> fechaEmision { get; set; }
    	[DataMember]
        public Nullable<int> idForebi { get; set; }
    	[DataMember]
        public string numForebi { get; set; }
    	[DataMember]
        public Nullable<int> idCuaCom { get; set; }
    	[DataMember]
        public string numCuaCom { get; set; }
    	[DataMember]
        public Nullable<int> idProveedor { get; set; }
    	[DataMember]
        public string ruc { get; set; }
    	[DataMember]
        public string razonSocial { get; set; }
    	[DataMember]
        public string direccion { get; set; }
    	[DataMember]
        public string justificacion { get; set; }
    	[DataMember]
        public Nullable<int> idSede { get; set; }
    	[DataMember]
        public Nullable<bool> esAgrupado { get; set; }
    	[DataMember]
        public Nullable<bool> esAprobado { get; set; }
    	[DataMember]
        public Nullable<bool> esPeriodica { get; set; }
    	[DataMember]
        public Nullable<bool> tieneOrden { get; set; }
    	[DataMember]
        public Nullable<bool> esAnual { get; set; }
    	[DataMember]
        public int idSubpresupuesto { get; set; }
    	[DataMember]
        public string desSubpresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idPresupuesto { get; set; }
    	[DataMember]
        public string desPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> idGruPre { get; set; }
    	[DataMember]
        public string desGrupoPresupuesto { get; set; }
    	[DataMember]
        public Nullable<int> estado { get; set; }
    	[DataMember]
        public string desEstado { get; set; }
    }
}
