//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Negocio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class vCotizacionDetalleCompra
    {
    	[DataMember]
        public int idCotDet { get; set; }
    	[DataMember]
        public Nullable<int> idCotizacion { get; set; }
    	[DataMember]
        public Nullable<int> orden { get; set; }
    	[DataMember]
        public Nullable<int> idProducto { get; set; }
    	[DataMember]
        public string desProducto { get; set; }
    	[DataMember]
        public string detalle { get; set; }
    	[DataMember]
        public string unidad { get; set; }
    	[DataMember]
        public Nullable<decimal> cantidad { get; set; }
    	[DataMember]
        public Nullable<decimal> precio { get; set; }
    	[DataMember]
        public Nullable<decimal> importe { get; set; }
    	[DataMember]
        public Nullable<int> idForebiDet { get; set; }
    	[DataMember]
        public Nullable<bool> esAprobado { get; set; }
    }
}
