//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIA_Presupuesto.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIA_Presupuesto.Datos.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR.
        /// </summary>
        internal static string Constante_Inicio {
            get {
                return ResourceManager.GetString("Constante_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARAR.
        /// </summary>
        internal static string Constante_Parar {
            get {
                return ResourceManager.GetString("Constante_Parar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal no puede ser null en AdministracionTiempoVidaPorEjecucionContexto.
        /// </summary>
        internal static string excepcion_AdministracionTiempoVidaPorEjecucionContexto_PrincipalNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_AdministracionTiempoVidaPorEjecucionContexto_PrincipalNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de seguimiento no puede ser nulo.
        /// </summary>
        internal static string excepcion_AdministradorDeSeguimientoNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_AdministradorDeSeguimientoNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento es nulo.
        /// </summary>
        internal static string excepcion_ArgumentoElementoInvalido {
            get {
                return ResourceManager.GetString("excepcion_ArgumentoElementoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CantidadPagina es menor a cero.
        /// </summary>
        internal static string excepcion_CantidadPaginaInvalida {
            get {
                return ResourceManager.GetString("excepcion_CantidadPaginaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de página no es válido.
        /// </summary>
        internal static string excepcion_CantidadPaginaInvalida1 {
            get {
                return ResourceManager.GetString("excepcion_CantidadPaginaInvalida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedor no puede ser nulo.
        /// </summary>
        internal static string excepcion_ContenedorNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_ContenedorNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede realizar la transferencia, número de cuenta no válido o una cuenta está bloqueada.
        /// </summary>
        internal static string excepcion_CuentaNoValidaParaLaTransferencia {
            get {
                return ResourceManager.GetString("excepcion_CuentaNoValidaParaLaTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominador Inválido.
        /// </summary>
        internal static string excepcion_DenominadorInvalido {
            get {
                return ResourceManager.GetString("excepcion_DenominadorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del Producto Inválido.
        /// </summary>
        internal static string excepcion_DescripcionProductoInvalido {
            get {
                return ResourceManager.GetString("excepcion_DescripcionProductoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IndicePagina * CantidadPagina producen excepción de desbordamiento.
        /// </summary>
        internal static string excepcion_ElementosNoValidosEnLaPagina {
            get {
                return ResourceManager.GetString("excepcion_ElementosNoValidosEnLaPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especificación no puede ser nulo.
        /// </summary>
        internal static string excepcion_EspecificacionEsNull {
            get {
                return ResourceManager.GetString("excepcion_EspecificacionEsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de expresión es nulo o no es una función de expresión válida.
        /// </summary>
        internal static string excepcion_ExpresiondeRutaNoValida {
            get {
                return ResourceManager.GetString("excepcion_ExpresiondeRutaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión de filtro no puede ser nulo.
        /// </summary>
        internal static string excepcion_FilTroNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_FilTroNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IndicePagina es menor a cero.
        /// </summary>
        internal static string excepcion_IndicePaginaInvalida {
            get {
                return ResourceManager.GetString("excepcion_IndicePaginaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indice de página inválida.
        /// </summary>
        internal static string excepcion_IndicePaginaInvalida1 {
            get {
                return ResourceManager.GetString("excepcion_IndicePaginaInvalida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta de inclusion no puede ser una cadena nula o vacía.
        /// </summary>
        internal static string excepcion_laRutaAbarcadaNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_laRutaAbarcadaNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dependencia de este objeto es una referencia nula.
        /// </summary>
        internal static string excepcion_LasDependenciasNoEstanInicializadas {
            get {
                return ResourceManager.GetString("excepcion_LasDependenciasNoEstanInicializadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Inválido de Seguimiento .
        /// </summary>
        internal static string excepcion_MensajeInvalidoSeguimiento {
            get {
                return ResourceManager.GetString("excepcion_MensajeInvalidoSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo Inválido.
        /// </summary>
        internal static string excepcion_ModeloInvalido {
            get {
                return ResourceManager.GetString("excepcion_ModeloInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OrdenarPorExpresion no puede ser nulo.
        /// </summary>
        internal static string excepcion_OrdenarPorExpresionNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_OrdenarPorExpresionNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede realizar esta operation.ChangeTracker es nulo o ObjectState no es válido para esta operación.
        /// </summary>
        internal static string excepcion_seguidordeCambio_esNulooEstadoNoEsCorrecto {
            get {
                return ResourceManager.GetString("excepcion_seguidordeCambio_esNulooEstadoNoEsCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Inválida.
        /// </summary>
        internal static string excepcion_UnidadInvalido {
            get {
                return ResourceManager.GetString("excepcion_UnidadInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento actualizado de tipo {0}.
        /// </summary>
        internal static string traza_ActualizarElementoaRepositorio {
            get {
                return ResourceManager.GetString("traza_ActualizarElementoaRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objejo agregado de tipo {0} en el repositorio.
        /// </summary>
        internal static string traza_AgregarElementoRepositorio {
            get {
                return ResourceManager.GetString("traza_AgregarElementoRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objejo agregado de tipo: {0} con ID: {1}, en el repositorio.
        /// </summary>
        internal static string traza_AgregarElementoRepositorioID {
            get {
                return ResourceManager.GetString("traza_AgregarElementoRepositorioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicado Cambios de tipo {0} en el repositorio.
        /// </summary>
        internal static string traza_AplicarCambiosElementoRepositorio {
            get {
                return ResourceManager.GetString("traza_AplicarCambiosElementoRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se aplicaron cambios al tipo: {0}, ID: {1}.
        /// </summary>
        internal static string traza_AplicarCambiosElementoRepositorioID {
            get {
                return ResourceManager.GetString("traza_AplicarCambiosElementoRepositorioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar elemento del tipo {0}.
        /// </summary>
        internal static string traza_BuscarPorEspecificacion {
            get {
                return ResourceManager.GetString("traza_BuscarPorEspecificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repositorio creado para tipo {0}.
        /// </summary>
        internal static string traza_ConstruirRepositorio {
            get {
                return ResourceManager.GetString("traza_ConstruirRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto eliminado de tipo {0}.
        /// </summary>
        internal static string traza_EliminarElementoRepositorio {
            get {
                return ResourceManager.GetString("traza_EliminarElementoRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto eliminado de tipo {0} , ID: {1}.
        /// </summary>
        internal static string traza_EliminarElementoRepositorioID {
            get {
                return ResourceManager.GetString("traza_EliminarElementoRepositorioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtención de datos, Método: {0}, Tipo: {1}.
        /// </summary>
        internal static string traza_OtrosMetodosRepositorio {
            get {
                return ResourceManager.GetString("traza_OtrosMetodosRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TraerElementosFiltrados  llamado el objeto: {0}.
        /// </summary>
        internal static string traza_TraerElementoFiltradoPaginadoRepositorio {
            get {
                return ResourceManager.GetString("traza_TraerElementoFiltradoPaginadoRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TraerElementosFiltrados en el objeto : {0}.
        /// </summary>
        internal static string traza_TraerFiltradoElementoRepositorio {
            get {
                return ResourceManager.GetString("traza_TraerFiltradoElementoRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TraerElementosPaginados llamado en el repositorio de tipo  {0} with IndicePagina:{1},CantidadPaginat:{2},OrdenadoPor:{3}.
        /// </summary>
        internal static string traza_TraerPaginadoElementoRepositorio {
            get {
                return ResourceManager.GetString("traza_TraerPaginadoElementoRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traer elementos del repositorio de tipo {0}.
        /// </summary>
        internal static string traza_TraerPorEspecificacion {
            get {
                return ResourceManager.GetString("traza_TraerPorEspecificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traer todos llamado en el repositorio de tipo {0}.
        /// </summary>
        internal static string traza_TraerTodosRepositorio {
            get {
                return ResourceManager.GetString("traza_TraerTodosRepositorio", resourceCulture);
            }
        }
    }
}
